// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/asset/service.proto

package asset

import (
	v1 "github.com/cpay-dev/proto-go/blockchain/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       v1.Chain               `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3,enum=cpay.blockchain.v1.Chain" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_asset_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAssetsRequest) GetChainId() v1.Chain {
	if x != nil {
		return x.ChainId
	}
	return v1.Chain(0)
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_asset_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GetAssetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetPriceRequest) Reset() {
	*x = GetAssetPriceRequest{}
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetPriceRequest) ProtoMessage() {}

func (x *GetAssetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetAssetPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_asset_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssetPriceRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type GetAssetPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetPriceResponse) Reset() {
	*x = GetAssetPriceResponse{}
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetPriceResponse) ProtoMessage() {}

func (x *GetAssetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_asset_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetPriceResponse.ProtoReflect.Descriptor instead.
func (*GetAssetPriceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_asset_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetPriceResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

var File_api_v1_merchant_asset_service_proto protoreflect.FileDescriptor

const file_api_v1_merchant_asset_service_proto_rawDesc = "" +
	"\n" +
	"#api/v1/merchant/asset/service.proto\x12\x1acpay.api.v1.merchant.asset\x1a!api/v1/merchant/asset/asset.proto\x1a\x19blockchain/v1/chain.proto\"I\n" +
	"\x11ListAssetsRequest\x124\n" +
	"\bchain_id\x18\x01 \x01(\x0e2\x19.cpay.blockchain.v1.ChainR\achainId\"O\n" +
	"\x12ListAssetsResponse\x129\n" +
	"\x06assets\x18\x01 \x03(\v2!.cpay.api.v1.merchant.asset.AssetR\x06assets\"1\n" +
	"\x14GetAssetPriceRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"-\n" +
	"\x15GetAssetPriceResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price2\xf1\x01\n" +
	"\fAssetService\x12k\n" +
	"\n" +
	"ListAssets\x12-.cpay.api.v1.merchant.asset.ListAssetsRequest\x1a..cpay.api.v1.merchant.asset.ListAssetsResponse\x12t\n" +
	"\rGetAssetPrice\x120.cpay.api.v1.merchant.asset.GetAssetPriceRequest\x1a1.cpay.api.v1.merchant.asset.GetAssetPriceResponseB4Z2github.com/cpay-dev/proto-go/api/v1/merchant/assetb\x06proto3"

var (
	file_api_v1_merchant_asset_service_proto_rawDescOnce sync.Once
	file_api_v1_merchant_asset_service_proto_rawDescData []byte
)

func file_api_v1_merchant_asset_service_proto_rawDescGZIP() []byte {
	file_api_v1_merchant_asset_service_proto_rawDescOnce.Do(func() {
		file_api_v1_merchant_asset_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_merchant_asset_service_proto_rawDesc), len(file_api_v1_merchant_asset_service_proto_rawDesc)))
	})
	return file_api_v1_merchant_asset_service_proto_rawDescData
}

var file_api_v1_merchant_asset_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_merchant_asset_service_proto_goTypes = []any{
	(*ListAssetsRequest)(nil),     // 0: cpay.api.v1.merchant.asset.ListAssetsRequest
	(*ListAssetsResponse)(nil),    // 1: cpay.api.v1.merchant.asset.ListAssetsResponse
	(*GetAssetPriceRequest)(nil),  // 2: cpay.api.v1.merchant.asset.GetAssetPriceRequest
	(*GetAssetPriceResponse)(nil), // 3: cpay.api.v1.merchant.asset.GetAssetPriceResponse
	(v1.Chain)(0),                 // 4: cpay.blockchain.v1.Chain
	(*Asset)(nil),                 // 5: cpay.api.v1.merchant.asset.Asset
}
var file_api_v1_merchant_asset_service_proto_depIdxs = []int32{
	4, // 0: cpay.api.v1.merchant.asset.ListAssetsRequest.chain_id:type_name -> cpay.blockchain.v1.Chain
	5, // 1: cpay.api.v1.merchant.asset.ListAssetsResponse.assets:type_name -> cpay.api.v1.merchant.asset.Asset
	0, // 2: cpay.api.v1.merchant.asset.AssetService.ListAssets:input_type -> cpay.api.v1.merchant.asset.ListAssetsRequest
	2, // 3: cpay.api.v1.merchant.asset.AssetService.GetAssetPrice:input_type -> cpay.api.v1.merchant.asset.GetAssetPriceRequest
	1, // 4: cpay.api.v1.merchant.asset.AssetService.ListAssets:output_type -> cpay.api.v1.merchant.asset.ListAssetsResponse
	3, // 5: cpay.api.v1.merchant.asset.AssetService.GetAssetPrice:output_type -> cpay.api.v1.merchant.asset.GetAssetPriceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_asset_service_proto_init() }
func file_api_v1_merchant_asset_service_proto_init() {
	if File_api_v1_merchant_asset_service_proto != nil {
		return
	}
	file_api_v1_merchant_asset_asset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_asset_service_proto_rawDesc), len(file_api_v1_merchant_asset_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_merchant_asset_service_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_asset_service_proto_depIdxs,
		MessageInfos:      file_api_v1_merchant_asset_service_proto_msgTypes,
	}.Build()
	File_api_v1_merchant_asset_service_proto = out.File
	file_api_v1_merchant_asset_service_proto_goTypes = nil
	file_api_v1_merchant_asset_service_proto_depIdxs = nil
}
