// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/indexer/block.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Chain             Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=cpay.blockchain.v1.indexer.Chain" json:"chain,omitempty"`
	ConfirmationLevel ConfirmationLevel      `protobuf:"varint,2,opt,name=confirmation_level,json=confirmationLevel,proto3,enum=cpay.blockchain.v1.indexer.ConfirmationLevel" json:"confirmation_level,omitempty"`
	BlockHash         string                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber       uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockTimestamp    uint64                 `protobuf:"varint,5,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	// Types that are valid to be assigned to Transactions:
	//
	//	*Block_EvmTransactions
	Transactions  isBlock_Transactions `protobuf_oneof:"transactions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *Block) GetConfirmationLevel() ConfirmationLevel {
	if x != nil {
		return x.ConfirmationLevel
	}
	return ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED
}

func (x *Block) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *Block) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Block) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

func (x *Block) GetTransactions() isBlock_Transactions {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetEvmTransactions() *EVMTransactions {
	if x != nil {
		if x, ok := x.Transactions.(*Block_EvmTransactions); ok {
			return x.EvmTransactions
		}
	}
	return nil
}

type isBlock_Transactions interface {
	isBlock_Transactions()
}

type Block_EvmTransactions struct {
	EvmTransactions *EVMTransactions `protobuf:"bytes,6,opt,name=evm_transactions,json=evmTransactions,proto3,oneof"`
}

func (*Block_EvmTransactions) isBlock_Transactions() {}

type EVMTransactions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SerializedTxs      []byte                 `protobuf:"bytes,1,opt,name=serialized_txs,json=serializedTxs,proto3" json:"serialized_txs,omitempty"`
	SerializedReceipts []byte                 `protobuf:"bytes,2,opt,name=serialized_receipts,json=serializedReceipts,proto3" json:"serialized_receipts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EVMTransactions) Reset() {
	*x = EVMTransactions{}
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EVMTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVMTransactions) ProtoMessage() {}

func (x *EVMTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVMTransactions.ProtoReflect.Descriptor instead.
func (*EVMTransactions) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_block_proto_rawDescGZIP(), []int{1}
}

func (x *EVMTransactions) GetSerializedTxs() []byte {
	if x != nil {
		return x.SerializedTxs
	}
	return nil
}

func (x *EVMTransactions) GetSerializedReceipts() []byte {
	if x != nil {
		return x.SerializedReceipts
	}
	return nil
}

var File_blockchain_v1_indexer_block_proto protoreflect.FileDescriptor

const file_blockchain_v1_indexer_block_proto_rawDesc = "" +
	"\n" +
	"!blockchain/v1/indexer/block.proto\x12\x1acpay.blockchain.v1.indexer\x1a!blockchain/v1/indexer/types.proto\"\xf3\x02\n" +
	"\x05Block\x127\n" +
	"\x05chain\x18\x01 \x01(\x0e2!.cpay.blockchain.v1.indexer.ChainR\x05chain\x12\\\n" +
	"\x12confirmation_level\x18\x02 \x01(\x0e2-.cpay.blockchain.v1.indexer.ConfirmationLevelR\x11confirmationLevel\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12'\n" +
	"\x0fblock_timestamp\x18\x05 \x01(\x04R\x0eblockTimestamp\x12X\n" +
	"\x10evm_transactions\x18\x06 \x01(\v2+.cpay.blockchain.v1.indexer.EVMTransactionsH\x00R\x0fevmTransactionsB\x0e\n" +
	"\ftransactions\"i\n" +
	"\x0fEVMTransactions\x12%\n" +
	"\x0eserialized_txs\x18\x01 \x01(\fR\rserializedTxs\x12/\n" +
	"\x13serialized_receipts\x18\x02 \x01(\fR\x12serializedReceiptsB4Z2github.com/cpay-dev/proto-go/blockchain/v1/indexerb\x06proto3"

var (
	file_blockchain_v1_indexer_block_proto_rawDescOnce sync.Once
	file_blockchain_v1_indexer_block_proto_rawDescData []byte
)

func file_blockchain_v1_indexer_block_proto_rawDescGZIP() []byte {
	file_blockchain_v1_indexer_block_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_indexer_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_block_proto_rawDesc), len(file_blockchain_v1_indexer_block_proto_rawDesc)))
	})
	return file_blockchain_v1_indexer_block_proto_rawDescData
}

var file_blockchain_v1_indexer_block_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_v1_indexer_block_proto_goTypes = []any{
	(*Block)(nil),           // 0: cpay.blockchain.v1.indexer.Block
	(*EVMTransactions)(nil), // 1: cpay.blockchain.v1.indexer.EVMTransactions
	(Chain)(0),              // 2: cpay.blockchain.v1.indexer.Chain
	(ConfirmationLevel)(0),  // 3: cpay.blockchain.v1.indexer.ConfirmationLevel
}
var file_blockchain_v1_indexer_block_proto_depIdxs = []int32{
	2, // 0: cpay.blockchain.v1.indexer.Block.chain:type_name -> cpay.blockchain.v1.indexer.Chain
	3, // 1: cpay.blockchain.v1.indexer.Block.confirmation_level:type_name -> cpay.blockchain.v1.indexer.ConfirmationLevel
	1, // 2: cpay.blockchain.v1.indexer.Block.evm_transactions:type_name -> cpay.blockchain.v1.indexer.EVMTransactions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blockchain_v1_indexer_block_proto_init() }
func file_blockchain_v1_indexer_block_proto_init() {
	if File_blockchain_v1_indexer_block_proto != nil {
		return
	}
	file_blockchain_v1_indexer_types_proto_init()
	file_blockchain_v1_indexer_block_proto_msgTypes[0].OneofWrappers = []any{
		(*Block_EvmTransactions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_block_proto_rawDesc), len(file_blockchain_v1_indexer_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_indexer_block_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_indexer_block_proto_depIdxs,
		MessageInfos:      file_blockchain_v1_indexer_block_proto_msgTypes,
	}.Build()
	File_blockchain_v1_indexer_block_proto = out.File
	file_blockchain_v1_indexer_block_proto_goTypes = nil
	file_blockchain_v1_indexer_block_proto_depIdxs = nil
}
