// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/indexer/block.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain int32

const (
	Chain_CHAIN_UNSPECIFIED Chain = 0
	Chain_CHAIN_EVM         Chain = 1
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "CHAIN_UNSPECIFIED",
		1: "CHAIN_EVM",
	}
	Chain_value = map[string]int32{
		"CHAIN_UNSPECIFIED": 0,
		"CHAIN_EVM":         1,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_indexer_block_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_blockchain_v1_indexer_block_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_block_proto_rawDescGZIP(), []int{0}
}

type ConfirmationLevel int32

const (
	ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED ConfirmationLevel = 0
	ConfirmationLevel_CONFIRMATION_LEVEL_PENDING     ConfirmationLevel = 1
	ConfirmationLevel_CONFIRMATION_LEVEL_SAFE        ConfirmationLevel = 2
	ConfirmationLevel_CONFIRMATION_LEVEL_FINALIZED   ConfirmationLevel = 3
)

// Enum value maps for ConfirmationLevel.
var (
	ConfirmationLevel_name = map[int32]string{
		0: "CONFIRMATION_LEVEL_UNSPECIFIED",
		1: "CONFIRMATION_LEVEL_PENDING",
		2: "CONFIRMATION_LEVEL_SAFE",
		3: "CONFIRMATION_LEVEL_FINALIZED",
	}
	ConfirmationLevel_value = map[string]int32{
		"CONFIRMATION_LEVEL_UNSPECIFIED": 0,
		"CONFIRMATION_LEVEL_PENDING":     1,
		"CONFIRMATION_LEVEL_SAFE":        2,
		"CONFIRMATION_LEVEL_FINALIZED":   3,
	}
)

func (x ConfirmationLevel) Enum() *ConfirmationLevel {
	p := new(ConfirmationLevel)
	*p = x
	return p
}

func (x ConfirmationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_indexer_block_proto_enumTypes[1].Descriptor()
}

func (ConfirmationLevel) Type() protoreflect.EnumType {
	return &file_blockchain_v1_indexer_block_proto_enumTypes[1]
}

func (x ConfirmationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationLevel.Descriptor instead.
func (ConfirmationLevel) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_block_proto_rawDescGZIP(), []int{1}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_block_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Chain             Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=cpay.blockchain.v1.indexer.Chain" json:"chain,omitempty"`
	ConfirmationLevel ConfirmationLevel      `protobuf:"varint,2,opt,name=confirmation_level,json=confirmationLevel,proto3,enum=cpay.blockchain.v1.indexer.ConfirmationLevel" json:"confirmation_level,omitempty"`
	BlockNumber       uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Transactions      []*Transaction         `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_indexer_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_block_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *Block) GetConfirmationLevel() ConfirmationLevel {
	if x != nil {
		return x.ConfirmationLevel
	}
	return ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED
}

func (x *Block) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_blockchain_v1_indexer_block_proto protoreflect.FileDescriptor

const file_blockchain_v1_indexer_block_proto_rawDesc = "" +
	"\n" +
	"!blockchain/v1/indexer/block.proto\x12\x1acpay.blockchain.v1.indexer\"&\n" +
	"\vTransaction\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\x8e\x02\n" +
	"\x05Block\x127\n" +
	"\x05chain\x18\x01 \x01(\x0e2!.cpay.blockchain.v1.indexer.ChainR\x05chain\x12\\\n" +
	"\x12confirmation_level\x18\x02 \x01(\x0e2-.cpay.blockchain.v1.indexer.ConfirmationLevelR\x11confirmationLevel\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12K\n" +
	"\ftransactions\x18\x04 \x03(\v2'.cpay.blockchain.v1.indexer.TransactionR\ftransactions*-\n" +
	"\x05Chain\x12\x15\n" +
	"\x11CHAIN_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCHAIN_EVM\x10\x01*\x96\x01\n" +
	"\x11ConfirmationLevel\x12\"\n" +
	"\x1eCONFIRMATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONFIRMATION_LEVEL_PENDING\x10\x01\x12\x1b\n" +
	"\x17CONFIRMATION_LEVEL_SAFE\x10\x02\x12 \n" +
	"\x1cCONFIRMATION_LEVEL_FINALIZED\x10\x03B4Z2github.com/cpay-dev/proto-go/blockchain/v1/indexerb\x06proto3"

var (
	file_blockchain_v1_indexer_block_proto_rawDescOnce sync.Once
	file_blockchain_v1_indexer_block_proto_rawDescData []byte
)

func file_blockchain_v1_indexer_block_proto_rawDescGZIP() []byte {
	file_blockchain_v1_indexer_block_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_indexer_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_block_proto_rawDesc), len(file_blockchain_v1_indexer_block_proto_rawDesc)))
	})
	return file_blockchain_v1_indexer_block_proto_rawDescData
}

var file_blockchain_v1_indexer_block_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blockchain_v1_indexer_block_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_v1_indexer_block_proto_goTypes = []any{
	(Chain)(0),             // 0: cpay.blockchain.v1.indexer.Chain
	(ConfirmationLevel)(0), // 1: cpay.blockchain.v1.indexer.ConfirmationLevel
	(*Transaction)(nil),    // 2: cpay.blockchain.v1.indexer.Transaction
	(*Block)(nil),          // 3: cpay.blockchain.v1.indexer.Block
}
var file_blockchain_v1_indexer_block_proto_depIdxs = []int32{
	0, // 0: cpay.blockchain.v1.indexer.Block.chain:type_name -> cpay.blockchain.v1.indexer.Chain
	1, // 1: cpay.blockchain.v1.indexer.Block.confirmation_level:type_name -> cpay.blockchain.v1.indexer.ConfirmationLevel
	2, // 2: cpay.blockchain.v1.indexer.Block.transactions:type_name -> cpay.blockchain.v1.indexer.Transaction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blockchain_v1_indexer_block_proto_init() }
func file_blockchain_v1_indexer_block_proto_init() {
	if File_blockchain_v1_indexer_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_block_proto_rawDesc), len(file_blockchain_v1_indexer_block_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_indexer_block_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_indexer_block_proto_depIdxs,
		EnumInfos:         file_blockchain_v1_indexer_block_proto_enumTypes,
		MessageInfos:      file_blockchain_v1_indexer_block_proto_msgTypes,
	}.Build()
	File_blockchain_v1_indexer_block_proto = out.File
	file_blockchain_v1_indexer_block_proto_goTypes = nil
	file_blockchain_v1_indexer_block_proto_depIdxs = nil
}
