// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/indexer/parsed-block.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParsedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockBase             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Transfers     []*ParsedTransfer      `protobuf:"bytes,2,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedBlock) Reset() {
	*x = ParsedBlock{}
	mi := &file_blockchain_v1_indexer_parsed_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedBlock) ProtoMessage() {}

func (x *ParsedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_indexer_parsed_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedBlock.ProtoReflect.Descriptor instead.
func (*ParsedBlock) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_parsed_block_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedBlock) GetBlock() *BlockBase {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ParsedBlock) GetTransfers() []*ParsedTransfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type ParsedTransfer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TxHash string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Amount string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	From   string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To     string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Index  uint64                 `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ParsedTransfer_Native
	//	*ParsedTransfer_Contract
	Kind          isParsedTransfer_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedTransfer) Reset() {
	*x = ParsedTransfer{}
	mi := &file_blockchain_v1_indexer_parsed_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTransfer) ProtoMessage() {}

func (x *ParsedTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_indexer_parsed_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTransfer.ProtoReflect.Descriptor instead.
func (*ParsedTransfer) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_parsed_block_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedTransfer) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ParsedTransfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ParsedTransfer) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ParsedTransfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ParsedTransfer) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ParsedTransfer) GetKind() isParsedTransfer_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ParsedTransfer) GetNative() bool {
	if x != nil {
		if x, ok := x.Kind.(*ParsedTransfer_Native); ok {
			return x.Native
		}
	}
	return false
}

func (x *ParsedTransfer) GetContract() string {
	if x != nil {
		if x, ok := x.Kind.(*ParsedTransfer_Contract); ok {
			return x.Contract
		}
	}
	return ""
}

type isParsedTransfer_Kind interface {
	isParsedTransfer_Kind()
}

type ParsedTransfer_Native struct {
	Native bool `protobuf:"varint,6,opt,name=native,proto3,oneof"`
}

type ParsedTransfer_Contract struct {
	Contract string `protobuf:"bytes,7,opt,name=contract,proto3,oneof"`
}

func (*ParsedTransfer_Native) isParsedTransfer_Kind() {}

func (*ParsedTransfer_Contract) isParsedTransfer_Kind() {}

var File_blockchain_v1_indexer_parsed_block_proto protoreflect.FileDescriptor

const file_blockchain_v1_indexer_parsed_block_proto_rawDesc = "" +
	"\n" +
	"(blockchain/v1/indexer/parsed-block.proto\x12\x1acpay.blockchain.v1.indexer\x1a!blockchain/v1/indexer/block.proto\"\x94\x01\n" +
	"\vParsedBlock\x12;\n" +
	"\x05block\x18\x01 \x01(\v2%.cpay.blockchain.v1.indexer.BlockBaseR\x05block\x12H\n" +
	"\ttransfers\x18\x02 \x03(\v2*.cpay.blockchain.v1.indexer.ParsedTransferR\ttransfers\"\xbb\x01\n" +
	"\x0eParsedTransfer\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x04R\x05index\x12\x18\n" +
	"\x06native\x18\x06 \x01(\bH\x00R\x06native\x12\x1c\n" +
	"\bcontract\x18\a \x01(\tH\x00R\bcontractB\x06\n" +
	"\x04kindB4Z2github.com/cpay-dev/proto-go/blockchain/v1/indexerb\x06proto3"

var (
	file_blockchain_v1_indexer_parsed_block_proto_rawDescOnce sync.Once
	file_blockchain_v1_indexer_parsed_block_proto_rawDescData []byte
)

func file_blockchain_v1_indexer_parsed_block_proto_rawDescGZIP() []byte {
	file_blockchain_v1_indexer_parsed_block_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_indexer_parsed_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_parsed_block_proto_rawDesc), len(file_blockchain_v1_indexer_parsed_block_proto_rawDesc)))
	})
	return file_blockchain_v1_indexer_parsed_block_proto_rawDescData
}

var file_blockchain_v1_indexer_parsed_block_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_v1_indexer_parsed_block_proto_goTypes = []any{
	(*ParsedBlock)(nil),    // 0: cpay.blockchain.v1.indexer.ParsedBlock
	(*ParsedTransfer)(nil), // 1: cpay.blockchain.v1.indexer.ParsedTransfer
	(*BlockBase)(nil),      // 2: cpay.blockchain.v1.indexer.BlockBase
}
var file_blockchain_v1_indexer_parsed_block_proto_depIdxs = []int32{
	2, // 0: cpay.blockchain.v1.indexer.ParsedBlock.block:type_name -> cpay.blockchain.v1.indexer.BlockBase
	1, // 1: cpay.blockchain.v1.indexer.ParsedBlock.transfers:type_name -> cpay.blockchain.v1.indexer.ParsedTransfer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blockchain_v1_indexer_parsed_block_proto_init() }
func file_blockchain_v1_indexer_parsed_block_proto_init() {
	if File_blockchain_v1_indexer_parsed_block_proto != nil {
		return
	}
	file_blockchain_v1_indexer_block_proto_init()
	file_blockchain_v1_indexer_parsed_block_proto_msgTypes[1].OneofWrappers = []any{
		(*ParsedTransfer_Native)(nil),
		(*ParsedTransfer_Contract)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_parsed_block_proto_rawDesc), len(file_blockchain_v1_indexer_parsed_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_indexer_parsed_block_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_indexer_parsed_block_proto_depIdxs,
		MessageInfos:      file_blockchain_v1_indexer_parsed_block_proto_msgTypes,
	}.Build()
	File_blockchain_v1_indexer_parsed_block_proto = out.File
	file_blockchain_v1_indexer_parsed_block_proto_goTypes = nil
	file_blockchain_v1_indexer_parsed_block_proto_depIdxs = nil
}
