// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/indexer/types.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain int32

const (
	Chain_CHAIN_UNSPECIFIED Chain = 0
	Chain_CHAIN_EVM         Chain = 1
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "CHAIN_UNSPECIFIED",
		1: "CHAIN_EVM",
	}
	Chain_value = map[string]int32{
		"CHAIN_UNSPECIFIED": 0,
		"CHAIN_EVM":         1,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_indexer_types_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_blockchain_v1_indexer_types_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_types_proto_rawDescGZIP(), []int{0}
}

type ConfirmationLevel int32

const (
	ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED ConfirmationLevel = 0
	ConfirmationLevel_CONFIRMATION_LEVEL_PENDING     ConfirmationLevel = 1
	ConfirmationLevel_CONFIRMATION_LEVEL_SAFE        ConfirmationLevel = 2
	ConfirmationLevel_CONFIRMATION_LEVEL_FINALIZED   ConfirmationLevel = 3
)

// Enum value maps for ConfirmationLevel.
var (
	ConfirmationLevel_name = map[int32]string{
		0: "CONFIRMATION_LEVEL_UNSPECIFIED",
		1: "CONFIRMATION_LEVEL_PENDING",
		2: "CONFIRMATION_LEVEL_SAFE",
		3: "CONFIRMATION_LEVEL_FINALIZED",
	}
	ConfirmationLevel_value = map[string]int32{
		"CONFIRMATION_LEVEL_UNSPECIFIED": 0,
		"CONFIRMATION_LEVEL_PENDING":     1,
		"CONFIRMATION_LEVEL_SAFE":        2,
		"CONFIRMATION_LEVEL_FINALIZED":   3,
	}
)

func (x ConfirmationLevel) Enum() *ConfirmationLevel {
	p := new(ConfirmationLevel)
	*p = x
	return p
}

func (x ConfirmationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_indexer_types_proto_enumTypes[1].Descriptor()
}

func (ConfirmationLevel) Type() protoreflect.EnumType {
	return &file_blockchain_v1_indexer_types_proto_enumTypes[1]
}

func (x ConfirmationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationLevel.Descriptor instead.
func (ConfirmationLevel) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_indexer_types_proto_rawDescGZIP(), []int{1}
}

var File_blockchain_v1_indexer_types_proto protoreflect.FileDescriptor

const file_blockchain_v1_indexer_types_proto_rawDesc = "" +
	"\n" +
	"!blockchain/v1/indexer/types.proto\x12\x1acpay.blockchain.v1.indexer*-\n" +
	"\x05Chain\x12\x15\n" +
	"\x11CHAIN_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCHAIN_EVM\x10\x01*\x96\x01\n" +
	"\x11ConfirmationLevel\x12\"\n" +
	"\x1eCONFIRMATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONFIRMATION_LEVEL_PENDING\x10\x01\x12\x1b\n" +
	"\x17CONFIRMATION_LEVEL_SAFE\x10\x02\x12 \n" +
	"\x1cCONFIRMATION_LEVEL_FINALIZED\x10\x03B4Z2github.com/cpay-dev/proto-go/blockchain/v1/indexerb\x06proto3"

var (
	file_blockchain_v1_indexer_types_proto_rawDescOnce sync.Once
	file_blockchain_v1_indexer_types_proto_rawDescData []byte
)

func file_blockchain_v1_indexer_types_proto_rawDescGZIP() []byte {
	file_blockchain_v1_indexer_types_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_indexer_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_types_proto_rawDesc), len(file_blockchain_v1_indexer_types_proto_rawDesc)))
	})
	return file_blockchain_v1_indexer_types_proto_rawDescData
}

var file_blockchain_v1_indexer_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blockchain_v1_indexer_types_proto_goTypes = []any{
	(Chain)(0),             // 0: cpay.blockchain.v1.indexer.Chain
	(ConfirmationLevel)(0), // 1: cpay.blockchain.v1.indexer.ConfirmationLevel
}
var file_blockchain_v1_indexer_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_v1_indexer_types_proto_init() }
func file_blockchain_v1_indexer_types_proto_init() {
	if File_blockchain_v1_indexer_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_indexer_types_proto_rawDesc), len(file_blockchain_v1_indexer_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_indexer_types_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_indexer_types_proto_depIdxs,
		EnumInfos:         file_blockchain_v1_indexer_types_proto_enumTypes,
	}.Build()
	File_blockchain_v1_indexer_types_proto = out.File
	file_blockchain_v1_indexer_types_proto_goTypes = nil
	file_blockchain_v1_indexer_types_proto_depIdxs = nil
}
