// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/chain/service.proto

package chain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListChainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsRequest) Reset() {
	*x = ListChainsRequest{}
	mi := &file_api_v1_merchant_chain_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsRequest) ProtoMessage() {}

func (x *ListChainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_chain_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsRequest.ProtoReflect.Descriptor instead.
func (*ListChainsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_chain_service_proto_rawDescGZIP(), []int{0}
}

type ListChainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*Chain               `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsResponse) Reset() {
	*x = ListChainsResponse{}
	mi := &file_api_v1_merchant_chain_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsResponse) ProtoMessage() {}

func (x *ListChainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_chain_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsResponse.ProtoReflect.Descriptor instead.
func (*ListChainsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_chain_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListChainsResponse) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

var File_api_v1_merchant_chain_service_proto protoreflect.FileDescriptor

const file_api_v1_merchant_chain_service_proto_rawDesc = "" +
	"\n" +
	"#api/v1/merchant/chain/service.proto\x12\x1acpay.api.v1.merchant.chain\x1a!api/v1/merchant/chain/chain.proto\"\x13\n" +
	"\x11ListChainsRequest\"O\n" +
	"\x12ListChainsResponse\x129\n" +
	"\x06chains\x18\x01 \x03(\v2!.cpay.api.v1.merchant.chain.ChainR\x06chains2{\n" +
	"\fChainService\x12k\n" +
	"\n" +
	"ListChains\x12-.cpay.api.v1.merchant.chain.ListChainsRequest\x1a..cpay.api.v1.merchant.chain.ListChainsResponseB4Z2github.com/cpay-dev/proto-go/api/v1/merchant/chainb\x06proto3"

var (
	file_api_v1_merchant_chain_service_proto_rawDescOnce sync.Once
	file_api_v1_merchant_chain_service_proto_rawDescData []byte
)

func file_api_v1_merchant_chain_service_proto_rawDescGZIP() []byte {
	file_api_v1_merchant_chain_service_proto_rawDescOnce.Do(func() {
		file_api_v1_merchant_chain_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_merchant_chain_service_proto_rawDesc), len(file_api_v1_merchant_chain_service_proto_rawDesc)))
	})
	return file_api_v1_merchant_chain_service_proto_rawDescData
}

var file_api_v1_merchant_chain_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_merchant_chain_service_proto_goTypes = []any{
	(*ListChainsRequest)(nil),  // 0: cpay.api.v1.merchant.chain.ListChainsRequest
	(*ListChainsResponse)(nil), // 1: cpay.api.v1.merchant.chain.ListChainsResponse
	(*Chain)(nil),              // 2: cpay.api.v1.merchant.chain.Chain
}
var file_api_v1_merchant_chain_service_proto_depIdxs = []int32{
	2, // 0: cpay.api.v1.merchant.chain.ListChainsResponse.chains:type_name -> cpay.api.v1.merchant.chain.Chain
	0, // 1: cpay.api.v1.merchant.chain.ChainService.ListChains:input_type -> cpay.api.v1.merchant.chain.ListChainsRequest
	1, // 2: cpay.api.v1.merchant.chain.ChainService.ListChains:output_type -> cpay.api.v1.merchant.chain.ListChainsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_chain_service_proto_init() }
func file_api_v1_merchant_chain_service_proto_init() {
	if File_api_v1_merchant_chain_service_proto != nil {
		return
	}
	file_api_v1_merchant_chain_chain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_chain_service_proto_rawDesc), len(file_api_v1_merchant_chain_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_merchant_chain_service_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_chain_service_proto_depIdxs,
		MessageInfos:      file_api_v1_merchant_chain_service_proto_msgTypes,
	}.Build()
	File_api_v1_merchant_chain_service_proto = out.File
	file_api_v1_merchant_chain_service_proto_goTypes = nil
	file_api_v1_merchant_chain_service_proto_depIdxs = nil
}
