// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/block.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmationLevel int32

const (
	ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED ConfirmationLevel = 0
	ConfirmationLevel_CONFIRMATION_LEVEL_PENDING     ConfirmationLevel = 1
	ConfirmationLevel_CONFIRMATION_LEVEL_SAFE        ConfirmationLevel = 2
	ConfirmationLevel_CONFIRMATION_LEVEL_FINALIZED   ConfirmationLevel = 3
)

// Enum value maps for ConfirmationLevel.
var (
	ConfirmationLevel_name = map[int32]string{
		0: "CONFIRMATION_LEVEL_UNSPECIFIED",
		1: "CONFIRMATION_LEVEL_PENDING",
		2: "CONFIRMATION_LEVEL_SAFE",
		3: "CONFIRMATION_LEVEL_FINALIZED",
	}
	ConfirmationLevel_value = map[string]int32{
		"CONFIRMATION_LEVEL_UNSPECIFIED": 0,
		"CONFIRMATION_LEVEL_PENDING":     1,
		"CONFIRMATION_LEVEL_SAFE":        2,
		"CONFIRMATION_LEVEL_FINALIZED":   3,
	}
)

func (x ConfirmationLevel) Enum() *ConfirmationLevel {
	p := new(ConfirmationLevel)
	*p = x
	return p
}

func (x ConfirmationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_block_proto_enumTypes[0].Descriptor()
}

func (ConfirmationLevel) Type() protoreflect.EnumType {
	return &file_blockchain_v1_block_proto_enumTypes[0]
}

func (x ConfirmationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationLevel.Descriptor instead.
func (ConfirmationLevel) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_block_proto_rawDescGZIP(), []int{0}
}

type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Chain             Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=cpay.blockchain.v1.Chain" json:"chain,omitempty"`
	ConfirmationLevel ConfirmationLevel      `protobuf:"varint,2,opt,name=confirmation_level,json=confirmationLevel,proto3,enum=cpay.blockchain.v1.ConfirmationLevel" json:"confirmation_level,omitempty"`
	BlockHash         string                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber       uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockTimestamp    uint64                 `protobuf:"varint,5,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blockchain_v1_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_v1_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blockchain_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *Block) GetConfirmationLevel() ConfirmationLevel {
	if x != nil {
		return x.ConfirmationLevel
	}
	return ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED
}

func (x *Block) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *Block) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Block) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

var File_blockchain_v1_block_proto protoreflect.FileDescriptor

const file_blockchain_v1_block_proto_rawDesc = "" +
	"\n" +
	"\x19blockchain/v1/block.proto\x12\x12cpay.blockchain.v1\x1a\x19blockchain/v1/chain.proto\"\xf9\x01\n" +
	"\x05Block\x12/\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x19.cpay.blockchain.v1.ChainR\x05chain\x12T\n" +
	"\x12confirmation_level\x18\x02 \x01(\x0e2%.cpay.blockchain.v1.ConfirmationLevelR\x11confirmationLevel\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12'\n" +
	"\x0fblock_timestamp\x18\x05 \x01(\x04R\x0eblockTimestamp*\x96\x01\n" +
	"\x11ConfirmationLevel\x12\"\n" +
	"\x1eCONFIRMATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONFIRMATION_LEVEL_PENDING\x10\x01\x12\x1b\n" +
	"\x17CONFIRMATION_LEVEL_SAFE\x10\x02\x12 \n" +
	"\x1cCONFIRMATION_LEVEL_FINALIZED\x10\x03B,Z*github.com/cpay-dev/proto-go/blockchain/v1b\x06proto3"

var (
	file_blockchain_v1_block_proto_rawDescOnce sync.Once
	file_blockchain_v1_block_proto_rawDescData []byte
)

func file_blockchain_v1_block_proto_rawDescGZIP() []byte {
	file_blockchain_v1_block_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_block_proto_rawDesc), len(file_blockchain_v1_block_proto_rawDesc)))
	})
	return file_blockchain_v1_block_proto_rawDescData
}

var file_blockchain_v1_block_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockchain_v1_block_proto_goTypes = []any{
	(ConfirmationLevel)(0), // 0: cpay.blockchain.v1.ConfirmationLevel
	(*Block)(nil),          // 1: cpay.blockchain.v1.Block
	(Chain)(0),             // 2: cpay.blockchain.v1.Chain
}
var file_blockchain_v1_block_proto_depIdxs = []int32{
	2, // 0: cpay.blockchain.v1.Block.chain:type_name -> cpay.blockchain.v1.Chain
	0, // 1: cpay.blockchain.v1.Block.confirmation_level:type_name -> cpay.blockchain.v1.ConfirmationLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blockchain_v1_block_proto_init() }
func file_blockchain_v1_block_proto_init() {
	if File_blockchain_v1_block_proto != nil {
		return
	}
	file_blockchain_v1_chain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_block_proto_rawDesc), len(file_blockchain_v1_block_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_block_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_block_proto_depIdxs,
		EnumInfos:         file_blockchain_v1_block_proto_enumTypes,
		MessageInfos:      file_blockchain_v1_block_proto_msgTypes,
	}.Build()
	File_blockchain_v1_block_proto = out.File
	file_blockchain_v1_block_proto_goTypes = nil
	file_blockchain_v1_block_proto_depIdxs = nil
}
