// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/block.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmationLevel int32

const (
	ConfirmationLevel_CONFIRMATION_LEVEL_UNSPECIFIED ConfirmationLevel = 0
	ConfirmationLevel_CONFIRMATION_LEVEL_PENDING     ConfirmationLevel = 1
	ConfirmationLevel_CONFIRMATION_LEVEL_SAFE        ConfirmationLevel = 2
	ConfirmationLevel_CONFIRMATION_LEVEL_FINALIZED   ConfirmationLevel = 3
)

// Enum value maps for ConfirmationLevel.
var (
	ConfirmationLevel_name = map[int32]string{
		0: "CONFIRMATION_LEVEL_UNSPECIFIED",
		1: "CONFIRMATION_LEVEL_PENDING",
		2: "CONFIRMATION_LEVEL_SAFE",
		3: "CONFIRMATION_LEVEL_FINALIZED",
	}
	ConfirmationLevel_value = map[string]int32{
		"CONFIRMATION_LEVEL_UNSPECIFIED": 0,
		"CONFIRMATION_LEVEL_PENDING":     1,
		"CONFIRMATION_LEVEL_SAFE":        2,
		"CONFIRMATION_LEVEL_FINALIZED":   3,
	}
)

func (x ConfirmationLevel) Enum() *ConfirmationLevel {
	p := new(ConfirmationLevel)
	*p = x
	return p
}

func (x ConfirmationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_block_proto_enumTypes[0].Descriptor()
}

func (ConfirmationLevel) Type() protoreflect.EnumType {
	return &file_blockchain_v1_block_proto_enumTypes[0]
}

func (x ConfirmationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationLevel.Descriptor instead.
func (ConfirmationLevel) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_block_proto_rawDescGZIP(), []int{0}
}

var File_blockchain_v1_block_proto protoreflect.FileDescriptor

const file_blockchain_v1_block_proto_rawDesc = "" +
	"\n" +
	"\x19blockchain/v1/block.proto\x12\x12cpay.blockchain.v1*\x96\x01\n" +
	"\x11ConfirmationLevel\x12\"\n" +
	"\x1eCONFIRMATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONFIRMATION_LEVEL_PENDING\x10\x01\x12\x1b\n" +
	"\x17CONFIRMATION_LEVEL_SAFE\x10\x02\x12 \n" +
	"\x1cCONFIRMATION_LEVEL_FINALIZED\x10\x03B,Z*github.com/cpay-dev/proto-go/blockchain/v1b\x06proto3"

var (
	file_blockchain_v1_block_proto_rawDescOnce sync.Once
	file_blockchain_v1_block_proto_rawDescData []byte
)

func file_blockchain_v1_block_proto_rawDescGZIP() []byte {
	file_blockchain_v1_block_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_block_proto_rawDesc), len(file_blockchain_v1_block_proto_rawDesc)))
	})
	return file_blockchain_v1_block_proto_rawDescData
}

var file_blockchain_v1_block_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_v1_block_proto_goTypes = []any{
	(ConfirmationLevel)(0), // 0: cpay.blockchain.v1.ConfirmationLevel
}
var file_blockchain_v1_block_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_v1_block_proto_init() }
func file_blockchain_v1_block_proto_init() {
	if File_blockchain_v1_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_block_proto_rawDesc), len(file_blockchain_v1_block_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_block_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_block_proto_depIdxs,
		EnumInfos:         file_blockchain_v1_block_proto_enumTypes,
	}.Build()
	File_blockchain_v1_block_proto = out.File
	file_blockchain_v1_block_proto_goTypes = nil
	file_blockchain_v1_block_proto_depIdxs = nil
}
