// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blockchain/v1/chain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain int32

const (
	Chain_CHAIN_UNSPECIFIED  Chain = 0
	Chain_CHAIN_ANY_BTC      Chain = 1
	Chain_CHAIN_ANY_EVM      Chain = 2
	Chain_CHAIN_ANY_SVM      Chain = 3
	Chain_CHAIN_BTC_BITCOIN  Chain = 31
	Chain_CHAIN_EVM_ETHEREUM Chain = 41
	Chain_CHAIN_EVM_ARBITRUM Chain = 42
	Chain_CHAIN_EVM_POLYGON  Chain = 43
	Chain_CHAIN_EVM_UNICHAIN Chain = 44
	Chain_CHAIN_SVM_SOLANA   Chain = 76
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0:  "CHAIN_UNSPECIFIED",
		1:  "CHAIN_ANY_BTC",
		2:  "CHAIN_ANY_EVM",
		3:  "CHAIN_ANY_SVM",
		31: "CHAIN_BTC_BITCOIN",
		41: "CHAIN_EVM_ETHEREUM",
		42: "CHAIN_EVM_ARBITRUM",
		43: "CHAIN_EVM_POLYGON",
		44: "CHAIN_EVM_UNICHAIN",
		76: "CHAIN_SVM_SOLANA",
	}
	Chain_value = map[string]int32{
		"CHAIN_UNSPECIFIED":  0,
		"CHAIN_ANY_BTC":      1,
		"CHAIN_ANY_EVM":      2,
		"CHAIN_ANY_SVM":      3,
		"CHAIN_BTC_BITCOIN":  31,
		"CHAIN_EVM_ETHEREUM": 41,
		"CHAIN_EVM_ARBITRUM": 42,
		"CHAIN_EVM_POLYGON":  43,
		"CHAIN_EVM_UNICHAIN": 44,
		"CHAIN_SVM_SOLANA":   76,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_v1_chain_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_blockchain_v1_chain_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_v1_chain_proto_rawDescGZIP(), []int{0}
}

var File_blockchain_v1_chain_proto protoreflect.FileDescriptor

const file_blockchain_v1_chain_proto_rawDesc = "" +
	"\n" +
	"\x19blockchain/v1/chain.proto\x12\x12cpay.blockchain.v1*\xf5\x01\n" +
	"\x05Chain\x12\x15\n" +
	"\x11CHAIN_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHAIN_ANY_BTC\x10\x01\x12\x11\n" +
	"\rCHAIN_ANY_EVM\x10\x02\x12\x11\n" +
	"\rCHAIN_ANY_SVM\x10\x03\x12\x15\n" +
	"\x11CHAIN_BTC_BITCOIN\x10\x1f\x12\x16\n" +
	"\x12CHAIN_EVM_ETHEREUM\x10)\x12\x16\n" +
	"\x12CHAIN_EVM_ARBITRUM\x10*\x12\x15\n" +
	"\x11CHAIN_EVM_POLYGON\x10+\x12\x16\n" +
	"\x12CHAIN_EVM_UNICHAIN\x10,\x12\x14\n" +
	"\x10CHAIN_SVM_SOLANA\x10L\"\x04\b\x04\x10\x1e\"\x04\b \x10(\"\x04\b-\x10KB,Z*github.com/cpay-dev/proto-go/blockchain/v1b\x06proto3"

var (
	file_blockchain_v1_chain_proto_rawDescOnce sync.Once
	file_blockchain_v1_chain_proto_rawDescData []byte
)

func file_blockchain_v1_chain_proto_rawDescGZIP() []byte {
	file_blockchain_v1_chain_proto_rawDescOnce.Do(func() {
		file_blockchain_v1_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockchain_v1_chain_proto_rawDesc), len(file_blockchain_v1_chain_proto_rawDesc)))
	})
	return file_blockchain_v1_chain_proto_rawDescData
}

var file_blockchain_v1_chain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_v1_chain_proto_goTypes = []any{
	(Chain)(0), // 0: cpay.blockchain.v1.Chain
}
var file_blockchain_v1_chain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_v1_chain_proto_init() }
func file_blockchain_v1_chain_proto_init() {
	if File_blockchain_v1_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockchain_v1_chain_proto_rawDesc), len(file_blockchain_v1_chain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_v1_chain_proto_goTypes,
		DependencyIndexes: file_blockchain_v1_chain_proto_depIdxs,
		EnumInfos:         file_blockchain_v1_chain_proto_enumTypes,
	}.Build()
	File_blockchain_v1_chain_proto = out.File
	file_blockchain_v1_chain_proto_goTypes = nil
	file_blockchain_v1_chain_proto_depIdxs = nil
}
