// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/blockchain/asset.proto

package blockchain

import (
	v1 "github.com/cpay-dev/proto-go/blockchain/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chain         v1.Chain               `protobuf:"varint,2,opt,name=chain,proto3,enum=cpay.blockchain.v1.Chain" json:"chain,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Metadata      *AssetMetadata         `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_api_v1_blockchain_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetChain() v1.Chain {
	if x != nil {
		return x.Chain
	}
	return v1.Chain(0)
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetMetadata() *AssetMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AssetMetadata struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Address  string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Decimals uint32                 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//
	//	*AssetMetadata_Evm
	//	*AssetMetadata_Svm
	Metadata      isAssetMetadata_Metadata `protobuf_oneof:"metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetMetadata) Reset() {
	*x = AssetMetadata{}
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetMetadata) ProtoMessage() {}

func (x *AssetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetMetadata.ProtoReflect.Descriptor instead.
func (*AssetMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1_blockchain_asset_proto_rawDescGZIP(), []int{1}
}

func (x *AssetMetadata) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AssetMetadata) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *AssetMetadata) GetMetadata() isAssetMetadata_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AssetMetadata) GetEvm() *AssetMetadataEVM {
	if x != nil {
		if x, ok := x.Metadata.(*AssetMetadata_Evm); ok {
			return x.Evm
		}
	}
	return nil
}

func (x *AssetMetadata) GetSvm() *AssetMetadataSVM {
	if x != nil {
		if x, ok := x.Metadata.(*AssetMetadata_Svm); ok {
			return x.Svm
		}
	}
	return nil
}

type isAssetMetadata_Metadata interface {
	isAssetMetadata_Metadata()
}

type AssetMetadata_Evm struct {
	Evm *AssetMetadataEVM `protobuf:"bytes,3,opt,name=evm,proto3,oneof"`
}

type AssetMetadata_Svm struct {
	Svm *AssetMetadataSVM `protobuf:"bytes,4,opt,name=svm,proto3,oneof"`
}

func (*AssetMetadata_Evm) isAssetMetadata_Metadata() {}

func (*AssetMetadata_Svm) isAssetMetadata_Metadata() {}

type AssetMetadataEVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetMetadataEVM) Reset() {
	*x = AssetMetadataEVM{}
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetMetadataEVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetMetadataEVM) ProtoMessage() {}

func (x *AssetMetadataEVM) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetMetadataEVM.ProtoReflect.Descriptor instead.
func (*AssetMetadataEVM) Descriptor() ([]byte, []int) {
	return file_api_v1_blockchain_asset_proto_rawDescGZIP(), []int{2}
}

type AssetMetadataSVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetMetadataSVM) Reset() {
	*x = AssetMetadataSVM{}
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetMetadataSVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetMetadataSVM) ProtoMessage() {}

func (x *AssetMetadataSVM) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_blockchain_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetMetadataSVM.ProtoReflect.Descriptor instead.
func (*AssetMetadataSVM) Descriptor() ([]byte, []int) {
	return file_api_v1_blockchain_asset_proto_rawDescGZIP(), []int{3}
}

var File_api_v1_blockchain_asset_proto protoreflect.FileDescriptor

const file_api_v1_blockchain_asset_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/v1/blockchain/asset.proto\x12\x16cpay.api.v1.blockchain\x1a\x19blockchain/v1/chain.proto\"\xb7\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x05chain\x18\x02 \x01(\x0e2\x19.cpay.blockchain.v1.ChainR\x05chain\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12A\n" +
	"\bmetadata\x18\x05 \x01(\v2%.cpay.api.v1.blockchain.AssetMetadataR\bmetadata\"\xcd\x01\n" +
	"\rAssetMetadata\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12<\n" +
	"\x03evm\x18\x03 \x01(\v2(.cpay.api.v1.blockchain.AssetMetadataEVMH\x00R\x03evm\x12<\n" +
	"\x03svm\x18\x04 \x01(\v2(.cpay.api.v1.blockchain.AssetMetadataSVMH\x00R\x03svmB\n" +
	"\n" +
	"\bmetadata\"\x12\n" +
	"\x10AssetMetadataEVM\"\x12\n" +
	"\x10AssetMetadataSVMB0Z.github.com/cpay-dev/proto-go/api/v1/blockchainb\x06proto3"

var (
	file_api_v1_blockchain_asset_proto_rawDescOnce sync.Once
	file_api_v1_blockchain_asset_proto_rawDescData []byte
)

func file_api_v1_blockchain_asset_proto_rawDescGZIP() []byte {
	file_api_v1_blockchain_asset_proto_rawDescOnce.Do(func() {
		file_api_v1_blockchain_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_blockchain_asset_proto_rawDesc), len(file_api_v1_blockchain_asset_proto_rawDesc)))
	})
	return file_api_v1_blockchain_asset_proto_rawDescData
}

var file_api_v1_blockchain_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_blockchain_asset_proto_goTypes = []any{
	(*Asset)(nil),            // 0: cpay.api.v1.blockchain.Asset
	(*AssetMetadata)(nil),    // 1: cpay.api.v1.blockchain.AssetMetadata
	(*AssetMetadataEVM)(nil), // 2: cpay.api.v1.blockchain.AssetMetadataEVM
	(*AssetMetadataSVM)(nil), // 3: cpay.api.v1.blockchain.AssetMetadataSVM
	(v1.Chain)(0),            // 4: cpay.blockchain.v1.Chain
}
var file_api_v1_blockchain_asset_proto_depIdxs = []int32{
	4, // 0: cpay.api.v1.blockchain.Asset.chain:type_name -> cpay.blockchain.v1.Chain
	1, // 1: cpay.api.v1.blockchain.Asset.metadata:type_name -> cpay.api.v1.blockchain.AssetMetadata
	2, // 2: cpay.api.v1.blockchain.AssetMetadata.evm:type_name -> cpay.api.v1.blockchain.AssetMetadataEVM
	3, // 3: cpay.api.v1.blockchain.AssetMetadata.svm:type_name -> cpay.api.v1.blockchain.AssetMetadataSVM
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_blockchain_asset_proto_init() }
func file_api_v1_blockchain_asset_proto_init() {
	if File_api_v1_blockchain_asset_proto != nil {
		return
	}
	file_api_v1_blockchain_asset_proto_msgTypes[1].OneofWrappers = []any{
		(*AssetMetadata_Evm)(nil),
		(*AssetMetadata_Svm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_blockchain_asset_proto_rawDesc), len(file_api_v1_blockchain_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_blockchain_asset_proto_goTypes,
		DependencyIndexes: file_api_v1_blockchain_asset_proto_depIdxs,
		MessageInfos:      file_api_v1_blockchain_asset_proto_msgTypes,
	}.Build()
	File_api_v1_blockchain_asset_proto = out.File
	file_api_v1_blockchain_asset_proto_goTypes = nil
	file_api_v1_blockchain_asset_proto_depIdxs = nil
}
