// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/blockchain/chain_id.proto

package blockchain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainID int32

const (
	ChainID_CHAIN_ID_UNSPECIFIED  ChainID = 0
	ChainID_CHAIN_ID_ANY          ChainID = 1
	ChainID_CHAIN_ID_ANY_BTC      ChainID = 2
	ChainID_CHAIN_ID_ANY_EVM      ChainID = 3
	ChainID_CHAIN_ID_ANY_SVM      ChainID = 4
	ChainID_CHAIN_ID_BTC_BITCOIN  ChainID = 31
	ChainID_CHAIN_ID_EVM_ETHEREUM ChainID = 41
	ChainID_CHAIN_ID_EVM_ARBITRUM ChainID = 42
	ChainID_CHAIN_ID_EVM_POLYGON  ChainID = 43
	ChainID_CHAIN_ID_EVM_UNICHAIN ChainID = 44
	ChainID_CHAIN_ID_SVM_SOLANA   ChainID = 76
)

// Enum value maps for ChainID.
var (
	ChainID_name = map[int32]string{
		0:  "CHAIN_ID_UNSPECIFIED",
		1:  "CHAIN_ID_ANY",
		2:  "CHAIN_ID_ANY_BTC",
		3:  "CHAIN_ID_ANY_EVM",
		4:  "CHAIN_ID_ANY_SVM",
		31: "CHAIN_ID_BTC_BITCOIN",
		41: "CHAIN_ID_EVM_ETHEREUM",
		42: "CHAIN_ID_EVM_ARBITRUM",
		43: "CHAIN_ID_EVM_POLYGON",
		44: "CHAIN_ID_EVM_UNICHAIN",
		76: "CHAIN_ID_SVM_SOLANA",
	}
	ChainID_value = map[string]int32{
		"CHAIN_ID_UNSPECIFIED":  0,
		"CHAIN_ID_ANY":          1,
		"CHAIN_ID_ANY_BTC":      2,
		"CHAIN_ID_ANY_EVM":      3,
		"CHAIN_ID_ANY_SVM":      4,
		"CHAIN_ID_BTC_BITCOIN":  31,
		"CHAIN_ID_EVM_ETHEREUM": 41,
		"CHAIN_ID_EVM_ARBITRUM": 42,
		"CHAIN_ID_EVM_POLYGON":  43,
		"CHAIN_ID_EVM_UNICHAIN": 44,
		"CHAIN_ID_SVM_SOLANA":   76,
	}
)

func (x ChainID) Enum() *ChainID {
	p := new(ChainID)
	*p = x
	return p
}

func (x ChainID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainID) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_blockchain_chain_id_proto_enumTypes[0].Descriptor()
}

func (ChainID) Type() protoreflect.EnumType {
	return &file_api_v1_blockchain_chain_id_proto_enumTypes[0]
}

func (x ChainID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainID.Descriptor instead.
func (ChainID) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_blockchain_chain_id_proto_rawDescGZIP(), []int{0}
}

var File_api_v1_blockchain_chain_id_proto protoreflect.FileDescriptor

const file_api_v1_blockchain_chain_id_proto_rawDesc = "" +
	"\n" +
	" api/v1/blockchain/chain_id.proto\x12\x16cpay.api.v1.blockchain*\xa7\x02\n" +
	"\aChainID\x12\x18\n" +
	"\x14CHAIN_ID_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHAIN_ID_ANY\x10\x01\x12\x14\n" +
	"\x10CHAIN_ID_ANY_BTC\x10\x02\x12\x14\n" +
	"\x10CHAIN_ID_ANY_EVM\x10\x03\x12\x14\n" +
	"\x10CHAIN_ID_ANY_SVM\x10\x04\x12\x18\n" +
	"\x14CHAIN_ID_BTC_BITCOIN\x10\x1f\x12\x19\n" +
	"\x15CHAIN_ID_EVM_ETHEREUM\x10)\x12\x19\n" +
	"\x15CHAIN_ID_EVM_ARBITRUM\x10*\x12\x18\n" +
	"\x14CHAIN_ID_EVM_POLYGON\x10+\x12\x19\n" +
	"\x15CHAIN_ID_EVM_UNICHAIN\x10,\x12\x17\n" +
	"\x13CHAIN_ID_SVM_SOLANA\x10L\"\x04\b\x05\x10\x1e\"\x04\b \x10(\"\x04\b-\x10KB0Z.github.com/cpay-dev/proto-go/api/v1/blockchainb\x06proto3"

var (
	file_api_v1_blockchain_chain_id_proto_rawDescOnce sync.Once
	file_api_v1_blockchain_chain_id_proto_rawDescData []byte
)

func file_api_v1_blockchain_chain_id_proto_rawDescGZIP() []byte {
	file_api_v1_blockchain_chain_id_proto_rawDescOnce.Do(func() {
		file_api_v1_blockchain_chain_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_blockchain_chain_id_proto_rawDesc), len(file_api_v1_blockchain_chain_id_proto_rawDesc)))
	})
	return file_api_v1_blockchain_chain_id_proto_rawDescData
}

var file_api_v1_blockchain_chain_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_blockchain_chain_id_proto_goTypes = []any{
	(ChainID)(0), // 0: cpay.api.v1.blockchain.ChainID
}
var file_api_v1_blockchain_chain_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_blockchain_chain_id_proto_init() }
func file_api_v1_blockchain_chain_id_proto_init() {
	if File_api_v1_blockchain_chain_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_blockchain_chain_id_proto_rawDesc), len(file_api_v1_blockchain_chain_id_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_blockchain_chain_id_proto_goTypes,
		DependencyIndexes: file_api_v1_blockchain_chain_id_proto_depIdxs,
		EnumInfos:         file_api_v1_blockchain_chain_id_proto_enumTypes,
	}.Build()
	File_api_v1_blockchain_chain_id_proto = out.File
	file_api_v1_blockchain_chain_id_proto_goTypes = nil
	file_api_v1_blockchain_chain_id_proto_depIdxs = nil
}
