// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/payment-intent.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentIntentStatus int32

const (
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_UNSPECIFIED       PaymentIntentStatus = 0
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_AWAITING_PAYMENT  PaymentIntentStatus = 1
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_PAID              PaymentIntentStatus = 2
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_EXPIRED           PaymentIntentStatus = 3
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_AML_CHECK_PENDING PaymentIntentStatus = 4
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_AML_CHECK_FAILED  PaymentIntentStatus = 5
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_REFUND_PENDING    PaymentIntentStatus = 6
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_REFUNDED          PaymentIntentStatus = 7
)

// Enum value maps for PaymentIntentStatus.
var (
	PaymentIntentStatus_name = map[int32]string{
		0: "PAYMENT_INTENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_INTENT_STATUS_AWAITING_PAYMENT",
		2: "PAYMENT_INTENT_STATUS_PAID",
		3: "PAYMENT_INTENT_STATUS_EXPIRED",
		4: "PAYMENT_INTENT_STATUS_AML_CHECK_PENDING",
		5: "PAYMENT_INTENT_STATUS_AML_CHECK_FAILED",
		6: "PAYMENT_INTENT_STATUS_REFUND_PENDING",
		7: "PAYMENT_INTENT_STATUS_REFUNDED",
	}
	PaymentIntentStatus_value = map[string]int32{
		"PAYMENT_INTENT_STATUS_UNSPECIFIED":       0,
		"PAYMENT_INTENT_STATUS_AWAITING_PAYMENT":  1,
		"PAYMENT_INTENT_STATUS_PAID":              2,
		"PAYMENT_INTENT_STATUS_EXPIRED":           3,
		"PAYMENT_INTENT_STATUS_AML_CHECK_PENDING": 4,
		"PAYMENT_INTENT_STATUS_AML_CHECK_FAILED":  5,
		"PAYMENT_INTENT_STATUS_REFUND_PENDING":    6,
		"PAYMENT_INTENT_STATUS_REFUNDED":          7,
	}
)

func (x PaymentIntentStatus) Enum() *PaymentIntentStatus {
	p := new(PaymentIntentStatus)
	*p = x
	return p
}

func (x PaymentIntentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentIntentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_merchant_payment_intent_proto_enumTypes[0].Descriptor()
}

func (PaymentIntentStatus) Type() protoreflect.EnumType {
	return &file_api_v1_merchant_payment_intent_proto_enumTypes[0]
}

func (x PaymentIntentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentIntentStatus.Descriptor instead.
func (PaymentIntentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_intent_proto_rawDescGZIP(), []int{0}
}

type PaymentIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        PaymentIntentStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=cpay.api.v1.merchant.PaymentIntentStatus" json:"status,omitempty"`
	AssetId       string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AmountUsd     string                 `protobuf:"bytes,4,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	AmountAsset   string                 `protobuf:"bytes,5,opt,name=amount_asset,json=amountAsset,proto3" json:"amount_asset,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_api_v1_merchant_payment_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_intent_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetStatus() PaymentIntentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentIntentStatus_PAYMENT_INTENT_STATUS_UNSPECIFIED
}

func (x *PaymentIntent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PaymentIntent) GetAmountUsd() string {
	if x != nil {
		return x.AmountUsd
	}
	return ""
}

func (x *PaymentIntent) GetAmountAsset() string {
	if x != nil {
		return x.AmountAsset
	}
	return ""
}

func (x *PaymentIntent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentIntent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_v1_merchant_payment_intent_proto protoreflect.FileDescriptor

const file_api_v1_merchant_payment_intent_proto_rawDesc = "" +
	"\n" +
	"$api/v1/merchant/payment-intent.proto\x12\x14cpay.api.v1.merchant\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x02\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\x06status\x18\x02 \x01(\x0e2).cpay.api.v1.merchant.PaymentIntentStatusR\x06status\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x04 \x01(\tR\tamountUsd\x12!\n" +
	"\famount_asset\x18\x05 \x01(\tR\vamountAsset\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xd2\x02\n" +
	"\x13PaymentIntentStatus\x12%\n" +
	"!PAYMENT_INTENT_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&PAYMENT_INTENT_STATUS_AWAITING_PAYMENT\x10\x01\x12\x1e\n" +
	"\x1aPAYMENT_INTENT_STATUS_PAID\x10\x02\x12!\n" +
	"\x1dPAYMENT_INTENT_STATUS_EXPIRED\x10\x03\x12+\n" +
	"'PAYMENT_INTENT_STATUS_AML_CHECK_PENDING\x10\x04\x12*\n" +
	"&PAYMENT_INTENT_STATUS_AML_CHECK_FAILED\x10\x05\x12(\n" +
	"$PAYMENT_INTENT_STATUS_REFUND_PENDING\x10\x06\x12\"\n" +
	"\x1ePAYMENT_INTENT_STATUS_REFUNDED\x10\aB.Z,github.com/cpay-dev/proto-go/api/v1/merchantb\x06proto3"

var (
	file_api_v1_merchant_payment_intent_proto_rawDescOnce sync.Once
	file_api_v1_merchant_payment_intent_proto_rawDescData []byte
)

func file_api_v1_merchant_payment_intent_proto_rawDescGZIP() []byte {
	file_api_v1_merchant_payment_intent_proto_rawDescOnce.Do(func() {
		file_api_v1_merchant_payment_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_intent_proto_rawDesc), len(file_api_v1_merchant_payment_intent_proto_rawDesc)))
	})
	return file_api_v1_merchant_payment_intent_proto_rawDescData
}

var file_api_v1_merchant_payment_intent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_merchant_payment_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v1_merchant_payment_intent_proto_goTypes = []any{
	(PaymentIntentStatus)(0),      // 0: cpay.api.v1.merchant.PaymentIntentStatus
	(*PaymentIntent)(nil),         // 1: cpay.api.v1.merchant.PaymentIntent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_v1_merchant_payment_intent_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.merchant.PaymentIntent.status:type_name -> cpay.api.v1.merchant.PaymentIntentStatus
	2, // 1: cpay.api.v1.merchant.PaymentIntent.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: cpay.api.v1.merchant.PaymentIntent.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_payment_intent_proto_init() }
func file_api_v1_merchant_payment_intent_proto_init() {
	if File_api_v1_merchant_payment_intent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_intent_proto_rawDesc), len(file_api_v1_merchant_payment_intent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_merchant_payment_intent_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_payment_intent_proto_depIdxs,
		EnumInfos:         file_api_v1_merchant_payment_intent_proto_enumTypes,
		MessageInfos:      file_api_v1_merchant_payment_intent_proto_msgTypes,
	}.Build()
	File_api_v1_merchant_payment_intent_proto = out.File
	file_api_v1_merchant_payment_intent_proto_goTypes = nil
	file_api_v1_merchant_payment_intent_proto_depIdxs = nil
}
