// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/payment-intent-service.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentIntentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Types that are valid to be assigned to Amount:
	//
	//	*CreatePaymentIntentRequest_AmountUsd
	//	*CreatePaymentIntentRequest_AmountAsset
	Amount        isCreatePaymentIntentRequest_Amount `protobuf_oneof:"amount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_api_v1_merchant_payment_intent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_intent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_intent_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmount() isCreatePaymentIntentRequest_Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePaymentIntentRequest) GetAmountUsd() string {
	if x != nil {
		if x, ok := x.Amount.(*CreatePaymentIntentRequest_AmountUsd); ok {
			return x.AmountUsd
		}
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmountAsset() string {
	if x != nil {
		if x, ok := x.Amount.(*CreatePaymentIntentRequest_AmountAsset); ok {
			return x.AmountAsset
		}
	}
	return ""
}

type isCreatePaymentIntentRequest_Amount interface {
	isCreatePaymentIntentRequest_Amount()
}

type CreatePaymentIntentRequest_AmountUsd struct {
	AmountUsd string `protobuf:"bytes,2,opt,name=amount_usd,json=amountUsd,proto3,oneof"`
}

type CreatePaymentIntentRequest_AmountAsset struct {
	AmountAsset string `protobuf:"bytes,3,opt,name=amount_asset,json=amountAsset,proto3,oneof"`
}

func (*CreatePaymentIntentRequest_AmountUsd) isCreatePaymentIntentRequest_Amount() {}

func (*CreatePaymentIntentRequest_AmountAsset) isCreatePaymentIntentRequest_Amount() {}

type CreatePaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntent *PaymentIntent         `protobuf:"bytes,1,opt,name=payment_intent,json=paymentIntent,proto3" json:"payment_intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_api_v1_merchant_payment_intent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_intent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_intent_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetPaymentIntent() *PaymentIntent {
	if x != nil {
		return x.PaymentIntent
	}
	return nil
}

var File_api_v1_merchant_payment_intent_service_proto protoreflect.FileDescriptor

const file_api_v1_merchant_payment_intent_service_proto_rawDesc = "" +
	"\n" +
	",api/v1/merchant/payment-intent-service.proto\x12\x14cpay.api.v1.merchant\x1a$api/v1/merchant/payment-intent.proto\"\x87\x01\n" +
	"\x1aCreatePaymentIntentRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1f\n" +
	"\n" +
	"amount_usd\x18\x02 \x01(\tH\x00R\tamountUsd\x12#\n" +
	"\famount_asset\x18\x03 \x01(\tH\x00R\vamountAssetB\b\n" +
	"\x06amount\"i\n" +
	"\x1bCreatePaymentIntentResponse\x12J\n" +
	"\x0epayment_intent\x18\x01 \x01(\v2#.cpay.api.v1.merchant.PaymentIntentR\rpaymentIntent2\x92\x01\n" +
	"\x14PaymentIntentService\x12z\n" +
	"\x13CreatePaymentIntent\x120.cpay.api.v1.merchant.CreatePaymentIntentRequest\x1a1.cpay.api.v1.merchant.CreatePaymentIntentResponseB.Z,github.com/cpay-dev/proto-go/api/v1/merchantb\x06proto3"

var (
	file_api_v1_merchant_payment_intent_service_proto_rawDescOnce sync.Once
	file_api_v1_merchant_payment_intent_service_proto_rawDescData []byte
)

func file_api_v1_merchant_payment_intent_service_proto_rawDescGZIP() []byte {
	file_api_v1_merchant_payment_intent_service_proto_rawDescOnce.Do(func() {
		file_api_v1_merchant_payment_intent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_intent_service_proto_rawDesc), len(file_api_v1_merchant_payment_intent_service_proto_rawDesc)))
	})
	return file_api_v1_merchant_payment_intent_service_proto_rawDescData
}

var file_api_v1_merchant_payment_intent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_merchant_payment_intent_service_proto_goTypes = []any{
	(*CreatePaymentIntentRequest)(nil),  // 0: cpay.api.v1.merchant.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 1: cpay.api.v1.merchant.CreatePaymentIntentResponse
	(*PaymentIntent)(nil),               // 2: cpay.api.v1.merchant.PaymentIntent
}
var file_api_v1_merchant_payment_intent_service_proto_depIdxs = []int32{
	2, // 0: cpay.api.v1.merchant.CreatePaymentIntentResponse.payment_intent:type_name -> cpay.api.v1.merchant.PaymentIntent
	0, // 1: cpay.api.v1.merchant.PaymentIntentService.CreatePaymentIntent:input_type -> cpay.api.v1.merchant.CreatePaymentIntentRequest
	1, // 2: cpay.api.v1.merchant.PaymentIntentService.CreatePaymentIntent:output_type -> cpay.api.v1.merchant.CreatePaymentIntentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_payment_intent_service_proto_init() }
func file_api_v1_merchant_payment_intent_service_proto_init() {
	if File_api_v1_merchant_payment_intent_service_proto != nil {
		return
	}
	file_api_v1_merchant_payment_intent_proto_init()
	file_api_v1_merchant_payment_intent_service_proto_msgTypes[0].OneofWrappers = []any{
		(*CreatePaymentIntentRequest_AmountUsd)(nil),
		(*CreatePaymentIntentRequest_AmountAsset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_intent_service_proto_rawDesc), len(file_api_v1_merchant_payment_intent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_merchant_payment_intent_service_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_payment_intent_service_proto_depIdxs,
		MessageInfos:      file_api_v1_merchant_payment_intent_service_proto_msgTypes,
	}.Build()
	File_api_v1_merchant_payment_intent_service_proto = out.File
	file_api_v1_merchant_payment_intent_service_proto_goTypes = nil
	file_api_v1_merchant_payment_intent_service_proto_depIdxs = nil
}
