// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/v1/merchant/payment-intent-service.proto

package merchant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentIntentService_CreatePaymentIntent_FullMethodName = "/cpay.api.v1.merchant.PaymentIntentService/CreatePaymentIntent"
)

// PaymentIntentServiceClient is the client API for PaymentIntentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentIntentServiceClient interface {
	CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error)
}

type paymentIntentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentIntentServiceClient(cc grpc.ClientConnInterface) PaymentIntentServiceClient {
	return &paymentIntentServiceClient{cc}
}

func (c *paymentIntentServiceClient) CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_CreatePaymentIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentIntentServiceServer is the server API for PaymentIntentService service.
// All implementations must embed UnimplementedPaymentIntentServiceServer
// for forward compatibility.
type PaymentIntentServiceServer interface {
	CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error)
	mustEmbedUnimplementedPaymentIntentServiceServer()
}

// UnimplementedPaymentIntentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentIntentServiceServer struct{}

func (UnimplementedPaymentIntentServiceServer) CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentIntent not implemented")
}
func (UnimplementedPaymentIntentServiceServer) mustEmbedUnimplementedPaymentIntentServiceServer() {}
func (UnimplementedPaymentIntentServiceServer) testEmbeddedByValue()                              {}

// UnsafePaymentIntentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentIntentServiceServer will
// result in compilation errors.
type UnsafePaymentIntentServiceServer interface {
	mustEmbedUnimplementedPaymentIntentServiceServer()
}

func RegisterPaymentIntentServiceServer(s grpc.ServiceRegistrar, srv PaymentIntentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentIntentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentIntentService_ServiceDesc, srv)
}

func _PaymentIntentService_CreatePaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).CreatePaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_CreatePaymentIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).CreatePaymentIntent(ctx, req.(*CreatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentIntentService_ServiceDesc is the grpc.ServiceDesc for PaymentIntentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentIntentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cpay.api.v1.merchant.PaymentIntentService",
	HandlerType: (*PaymentIntentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePaymentIntent",
			Handler:    _PaymentIntentService_CreatePaymentIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/merchant/payment-intent-service.proto",
}
