// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/service.proto

package merchant

import (
	_ "github.com/cpay-dev/proto-go/blockchain/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_merchant_service_proto protoreflect.FileDescriptor

const file_api_v1_merchant_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/v1/merchant/service.proto\x12\x14cpay.api.v1.merchant\x1a\x1bapi/v1/merchant/asset.proto\x1a\x1bapi/v1/merchant/chain.proto\x1a$api/v1/merchant/payment-intent.proto\x1a\x19blockchain/v1/chain.proto2\xcf\x02\n" +
	"\x0fMerchantService\x12_\n" +
	"\n" +
	"ListChains\x12'.cpay.api.v1.merchant.ListChainsRequest\x1a(.cpay.api.v1.merchant.ListChainsResponse\x12_\n" +
	"\n" +
	"ListAssets\x12'.cpay.api.v1.merchant.ListAssetsRequest\x1a(.cpay.api.v1.merchant.ListAssetsResponse\x12z\n" +
	"\x13CreatePaymentIntent\x120.cpay.api.v1.merchant.CreatePaymentIntentRequest\x1a1.cpay.api.v1.merchant.CreatePaymentIntentResponseB.Z,github.com/cpay-dev/proto-go/api/v1/merchantb\x06proto3"

var file_api_v1_merchant_service_proto_goTypes = []any{
	(*ListChainsRequest)(nil),           // 0: cpay.api.v1.merchant.ListChainsRequest
	(*ListAssetsRequest)(nil),           // 1: cpay.api.v1.merchant.ListAssetsRequest
	(*CreatePaymentIntentRequest)(nil),  // 2: cpay.api.v1.merchant.CreatePaymentIntentRequest
	(*ListChainsResponse)(nil),          // 3: cpay.api.v1.merchant.ListChainsResponse
	(*ListAssetsResponse)(nil),          // 4: cpay.api.v1.merchant.ListAssetsResponse
	(*CreatePaymentIntentResponse)(nil), // 5: cpay.api.v1.merchant.CreatePaymentIntentResponse
}
var file_api_v1_merchant_service_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.merchant.MerchantService.ListChains:input_type -> cpay.api.v1.merchant.ListChainsRequest
	1, // 1: cpay.api.v1.merchant.MerchantService.ListAssets:input_type -> cpay.api.v1.merchant.ListAssetsRequest
	2, // 2: cpay.api.v1.merchant.MerchantService.CreatePaymentIntent:input_type -> cpay.api.v1.merchant.CreatePaymentIntentRequest
	3, // 3: cpay.api.v1.merchant.MerchantService.ListChains:output_type -> cpay.api.v1.merchant.ListChainsResponse
	4, // 4: cpay.api.v1.merchant.MerchantService.ListAssets:output_type -> cpay.api.v1.merchant.ListAssetsResponse
	5, // 5: cpay.api.v1.merchant.MerchantService.CreatePaymentIntent:output_type -> cpay.api.v1.merchant.CreatePaymentIntentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_service_proto_init() }
func file_api_v1_merchant_service_proto_init() {
	if File_api_v1_merchant_service_proto != nil {
		return
	}
	file_api_v1_merchant_asset_proto_init()
	file_api_v1_merchant_chain_proto_init()
	file_api_v1_merchant_payment_intent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_service_proto_rawDesc), len(file_api_v1_merchant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_merchant_service_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_service_proto_depIdxs,
	}.Build()
	File_api_v1_merchant_service_proto = out.File
	file_api_v1_merchant_service_proto_goTypes = nil
	file_api_v1_merchant_service_proto_depIdxs = nil
}
