// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/kms/service.proto

package kms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WrapKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TransitNonce  []byte                 `protobuf:"bytes,2,opt,name=transit_nonce,json=transitNonce,proto3" json:"transit_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapKeyRequest) Reset() {
	*x = WrapKeyRequest{}
	mi := &file_api_v1_kms_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapKeyRequest) ProtoMessage() {}

func (x *WrapKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kms_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapKeyRequest.ProtoReflect.Descriptor instead.
func (*WrapKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kms_service_proto_rawDescGZIP(), []int{0}
}

func (x *WrapKeyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WrapKeyRequest) GetTransitNonce() []byte {
	if x != nil {
		return x.TransitNonce
	}
	return nil
}

type WrapKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EncryptedData string                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapKeyResponse) Reset() {
	*x = WrapKeyResponse{}
	mi := &file_api_v1_kms_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapKeyResponse) ProtoMessage() {}

func (x *WrapKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kms_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapKeyResponse.ProtoReflect.Descriptor instead.
func (*WrapKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kms_service_proto_rawDescGZIP(), []int{1}
}

func (x *WrapKeyResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WrapKeyResponse) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

type UnwrapKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TransitNonce  []byte                 `protobuf:"bytes,3,opt,name=transit_nonce,json=transitNonce,proto3" json:"transit_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapKeyRequest) Reset() {
	*x = UnwrapKeyRequest{}
	mi := &file_api_v1_kms_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapKeyRequest) ProtoMessage() {}

func (x *UnwrapKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kms_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapKeyRequest.ProtoReflect.Descriptor instead.
func (*UnwrapKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kms_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnwrapKeyRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UnwrapKeyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UnwrapKeyRequest) GetTransitNonce() []byte {
	if x != nil {
		return x.TransitNonce
	}
	return nil
}

type UnwrapKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EncryptedData string                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapKeyResponse) Reset() {
	*x = UnwrapKeyResponse{}
	mi := &file_api_v1_kms_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapKeyResponse) ProtoMessage() {}

func (x *UnwrapKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kms_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapKeyResponse.ProtoReflect.Descriptor instead.
func (*UnwrapKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kms_service_proto_rawDescGZIP(), []int{3}
}

func (x *UnwrapKeyResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UnwrapKeyResponse) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

type RewrapKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldVersion    uint32                 `protobuf:"varint,1,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TransitNonce  []byte                 `protobuf:"bytes,3,opt,name=transit_nonce,json=transitNonce,proto3" json:"transit_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewrapKeyRequest) Reset() {
	*x = RewrapKeyRequest{}
	mi := &file_api_v1_kms_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewrapKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewrapKeyRequest) ProtoMessage() {}

func (x *RewrapKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kms_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewrapKeyRequest.ProtoReflect.Descriptor instead.
func (*RewrapKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kms_service_proto_rawDescGZIP(), []int{4}
}

func (x *RewrapKeyRequest) GetOldVersion() uint32 {
	if x != nil {
		return x.OldVersion
	}
	return 0
}

func (x *RewrapKeyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RewrapKeyRequest) GetTransitNonce() []byte {
	if x != nil {
		return x.TransitNonce
	}
	return nil
}

type RewrapKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewVersion    uint32                 `protobuf:"varint,1,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	EncryptedData string                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewrapKeyResponse) Reset() {
	*x = RewrapKeyResponse{}
	mi := &file_api_v1_kms_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewrapKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewrapKeyResponse) ProtoMessage() {}

func (x *RewrapKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kms_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewrapKeyResponse.ProtoReflect.Descriptor instead.
func (*RewrapKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kms_service_proto_rawDescGZIP(), []int{5}
}

func (x *RewrapKeyResponse) GetNewVersion() uint32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *RewrapKeyResponse) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

var File_api_v1_kms_service_proto protoreflect.FileDescriptor

const file_api_v1_kms_service_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/kms/service.proto\x12\x0fcpay.api.v1.kms\"I\n" +
	"\x0eWrapKeyRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12#\n" +
	"\rtransit_nonce\x18\x02 \x01(\fR\ftransitNonce\"R\n" +
	"\x0fWrapKeyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\tR\rencryptedData\"e\n" +
	"\x10UnwrapKeyRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12#\n" +
	"\rtransit_nonce\x18\x03 \x01(\fR\ftransitNonce\"T\n" +
	"\x11UnwrapKeyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\tR\rencryptedData\"l\n" +
	"\x10RewrapKeyRequest\x12\x1f\n" +
	"\vold_version\x18\x01 \x01(\rR\n" +
	"oldVersion\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12#\n" +
	"\rtransit_nonce\x18\x03 \x01(\fR\ftransitNonce\"[\n" +
	"\x11RewrapKeyResponse\x12\x1f\n" +
	"\vnew_version\x18\x01 \x01(\rR\n" +
	"newVersion\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\tR\rencryptedData2\x8c\x02\n" +
	"\x14KeyManagementService\x12L\n" +
	"\aWrapKey\x12\x1f.cpay.api.v1.kms.WrapKeyRequest\x1a .cpay.api.v1.kms.WrapKeyResponse\x12R\n" +
	"\tUnwrapKey\x12!.cpay.api.v1.kms.UnwrapKeyRequest\x1a\".cpay.api.v1.kms.UnwrapKeyResponse\x12R\n" +
	"\tRewrapKey\x12!.cpay.api.v1.kms.RewrapKeyRequest\x1a\".cpay.api.v1.kms.RewrapKeyResponseB)Z'github.com/cpay-dev/proto-go/api/v1/kmsb\x06proto3"

var (
	file_api_v1_kms_service_proto_rawDescOnce sync.Once
	file_api_v1_kms_service_proto_rawDescData []byte
)

func file_api_v1_kms_service_proto_rawDescGZIP() []byte {
	file_api_v1_kms_service_proto_rawDescOnce.Do(func() {
		file_api_v1_kms_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_kms_service_proto_rawDesc), len(file_api_v1_kms_service_proto_rawDesc)))
	})
	return file_api_v1_kms_service_proto_rawDescData
}

var file_api_v1_kms_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_kms_service_proto_goTypes = []any{
	(*WrapKeyRequest)(nil),    // 0: cpay.api.v1.kms.WrapKeyRequest
	(*WrapKeyResponse)(nil),   // 1: cpay.api.v1.kms.WrapKeyResponse
	(*UnwrapKeyRequest)(nil),  // 2: cpay.api.v1.kms.UnwrapKeyRequest
	(*UnwrapKeyResponse)(nil), // 3: cpay.api.v1.kms.UnwrapKeyResponse
	(*RewrapKeyRequest)(nil),  // 4: cpay.api.v1.kms.RewrapKeyRequest
	(*RewrapKeyResponse)(nil), // 5: cpay.api.v1.kms.RewrapKeyResponse
}
var file_api_v1_kms_service_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.kms.KeyManagementService.WrapKey:input_type -> cpay.api.v1.kms.WrapKeyRequest
	2, // 1: cpay.api.v1.kms.KeyManagementService.UnwrapKey:input_type -> cpay.api.v1.kms.UnwrapKeyRequest
	4, // 2: cpay.api.v1.kms.KeyManagementService.RewrapKey:input_type -> cpay.api.v1.kms.RewrapKeyRequest
	1, // 3: cpay.api.v1.kms.KeyManagementService.WrapKey:output_type -> cpay.api.v1.kms.WrapKeyResponse
	3, // 4: cpay.api.v1.kms.KeyManagementService.UnwrapKey:output_type -> cpay.api.v1.kms.UnwrapKeyResponse
	5, // 5: cpay.api.v1.kms.KeyManagementService.RewrapKey:output_type -> cpay.api.v1.kms.RewrapKeyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_kms_service_proto_init() }
func file_api_v1_kms_service_proto_init() {
	if File_api_v1_kms_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_kms_service_proto_rawDesc), len(file_api_v1_kms_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_kms_service_proto_goTypes,
		DependencyIndexes: file_api_v1_kms_service_proto_depIdxs,
		MessageInfos:      file_api_v1_kms_service_proto_msgTypes,
	}.Build()
	File_api_v1_kms_service_proto = out.File
	file_api_v1_kms_service_proto_goTypes = nil
	file_api_v1_kms_service_proto_depIdxs = nil
}
