// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/payment/intent.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntentStatus int32

const (
	IntentStatus_INTENT_STATUS_UNSPECIFIED       IntentStatus = 0
	IntentStatus_INTENT_STATUS_AWAITING_PAYMENT  IntentStatus = 1
	IntentStatus_INTENT_STATUS_PAID              IntentStatus = 2
	IntentStatus_INTENT_STATUS_EXPIRED           IntentStatus = 3
	IntentStatus_INTENT_STATUS_AML_CHECK_PENDING IntentStatus = 4
	IntentStatus_INTENT_STATUS_AML_CHECK_FAILED  IntentStatus = 5
	IntentStatus_INTENT_STATUS_REFUND_PENDING    IntentStatus = 6
	IntentStatus_INTENT_STATUS_REFUNDED          IntentStatus = 7
)

// Enum value maps for IntentStatus.
var (
	IntentStatus_name = map[int32]string{
		0: "INTENT_STATUS_UNSPECIFIED",
		1: "INTENT_STATUS_AWAITING_PAYMENT",
		2: "INTENT_STATUS_PAID",
		3: "INTENT_STATUS_EXPIRED",
		4: "INTENT_STATUS_AML_CHECK_PENDING",
		5: "INTENT_STATUS_AML_CHECK_FAILED",
		6: "INTENT_STATUS_REFUND_PENDING",
		7: "INTENT_STATUS_REFUNDED",
	}
	IntentStatus_value = map[string]int32{
		"INTENT_STATUS_UNSPECIFIED":       0,
		"INTENT_STATUS_AWAITING_PAYMENT":  1,
		"INTENT_STATUS_PAID":              2,
		"INTENT_STATUS_EXPIRED":           3,
		"INTENT_STATUS_AML_CHECK_PENDING": 4,
		"INTENT_STATUS_AML_CHECK_FAILED":  5,
		"INTENT_STATUS_REFUND_PENDING":    6,
		"INTENT_STATUS_REFUNDED":          7,
	}
)

func (x IntentStatus) Enum() *IntentStatus {
	p := new(IntentStatus)
	*p = x
	return p
}

func (x IntentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_merchant_payment_intent_proto_enumTypes[0].Descriptor()
}

func (IntentStatus) Type() protoreflect.EnumType {
	return &file_api_v1_merchant_payment_intent_proto_enumTypes[0]
}

func (x IntentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentStatus.Descriptor instead.
func (IntentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_intent_proto_rawDescGZIP(), []int{0}
}

type Intent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        IntentStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=cpay.api.v1.merchant.payment.IntentStatus" json:"status,omitempty"`
	AssetId       string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AmountUsd     string                 `protobuf:"bytes,4,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	AmountAsset   string                 `protobuf:"bytes,5,opt,name=amount_asset,json=amountAsset,proto3" json:"amount_asset,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_api_v1_merchant_payment_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_intent_proto_rawDescGZIP(), []int{0}
}

func (x *Intent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Intent) GetStatus() IntentStatus {
	if x != nil {
		return x.Status
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *Intent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Intent) GetAmountUsd() string {
	if x != nil {
		return x.AmountUsd
	}
	return ""
}

func (x *Intent) GetAmountAsset() string {
	if x != nil {
		return x.AmountAsset
	}
	return ""
}

func (x *Intent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Intent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_v1_merchant_payment_intent_proto protoreflect.FileDescriptor

const file_api_v1_merchant_payment_intent_proto_rawDesc = "" +
	"\n" +
	"$api/v1/merchant/payment/intent.proto\x12\x1ccpay.api.v1.merchant.payment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\x06Intent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\x06status\x18\x02 \x01(\x0e2*.cpay.api.v1.merchant.payment.IntentStatusR\x06status\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x04 \x01(\tR\tamountUsd\x12!\n" +
	"\famount_asset\x18\x05 \x01(\tR\vamountAsset\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x8b\x02\n" +
	"\fIntentStatus\x12\x1d\n" +
	"\x19INTENT_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eINTENT_STATUS_AWAITING_PAYMENT\x10\x01\x12\x16\n" +
	"\x12INTENT_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15INTENT_STATUS_EXPIRED\x10\x03\x12#\n" +
	"\x1fINTENT_STATUS_AML_CHECK_PENDING\x10\x04\x12\"\n" +
	"\x1eINTENT_STATUS_AML_CHECK_FAILED\x10\x05\x12 \n" +
	"\x1cINTENT_STATUS_REFUND_PENDING\x10\x06\x12\x1a\n" +
	"\x16INTENT_STATUS_REFUNDED\x10\aB6Z4github.com/cpay-dev/proto-go/api/v1/merchant/paymentb\x06proto3"

var (
	file_api_v1_merchant_payment_intent_proto_rawDescOnce sync.Once
	file_api_v1_merchant_payment_intent_proto_rawDescData []byte
)

func file_api_v1_merchant_payment_intent_proto_rawDescGZIP() []byte {
	file_api_v1_merchant_payment_intent_proto_rawDescOnce.Do(func() {
		file_api_v1_merchant_payment_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_intent_proto_rawDesc), len(file_api_v1_merchant_payment_intent_proto_rawDesc)))
	})
	return file_api_v1_merchant_payment_intent_proto_rawDescData
}

var file_api_v1_merchant_payment_intent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_merchant_payment_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v1_merchant_payment_intent_proto_goTypes = []any{
	(IntentStatus)(0),             // 0: cpay.api.v1.merchant.payment.IntentStatus
	(*Intent)(nil),                // 1: cpay.api.v1.merchant.payment.Intent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_v1_merchant_payment_intent_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.merchant.payment.Intent.status:type_name -> cpay.api.v1.merchant.payment.IntentStatus
	2, // 1: cpay.api.v1.merchant.payment.Intent.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: cpay.api.v1.merchant.payment.Intent.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_payment_intent_proto_init() }
func file_api_v1_merchant_payment_intent_proto_init() {
	if File_api_v1_merchant_payment_intent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_intent_proto_rawDesc), len(file_api_v1_merchant_payment_intent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_merchant_payment_intent_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_payment_intent_proto_depIdxs,
		EnumInfos:         file_api_v1_merchant_payment_intent_proto_enumTypes,
		MessageInfos:      file_api_v1_merchant_payment_intent_proto_msgTypes,
	}.Build()
	File_api_v1_merchant_payment_intent_proto = out.File
	file_api_v1_merchant_payment_intent_proto_goTypes = nil
	file_api_v1_merchant_payment_intent_proto_depIdxs = nil
}
