// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/merchant/payment/service.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIntentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Types that are valid to be assigned to Amount:
	//
	//	*CreateIntentRequest_AmountUsd
	//	*CreateIntentRequest_AmountAsset
	Amount        isCreateIntentRequest_Amount `protobuf_oneof:"amount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentRequest) Reset() {
	*x = CreateIntentRequest{}
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentRequest) ProtoMessage() {}

func (x *CreateIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateIntentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIntentRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateIntentRequest) GetAmount() isCreateIntentRequest_Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateIntentRequest) GetAmountUsd() string {
	if x != nil {
		if x, ok := x.Amount.(*CreateIntentRequest_AmountUsd); ok {
			return x.AmountUsd
		}
	}
	return ""
}

func (x *CreateIntentRequest) GetAmountAsset() string {
	if x != nil {
		if x, ok := x.Amount.(*CreateIntentRequest_AmountAsset); ok {
			return x.AmountAsset
		}
	}
	return ""
}

type isCreateIntentRequest_Amount interface {
	isCreateIntentRequest_Amount()
}

type CreateIntentRequest_AmountUsd struct {
	AmountUsd string `protobuf:"bytes,2,opt,name=amount_usd,json=amountUsd,proto3,oneof"`
}

type CreateIntentRequest_AmountAsset struct {
	AmountAsset string `protobuf:"bytes,3,opt,name=amount_asset,json=amountAsset,proto3,oneof"`
}

func (*CreateIntentRequest_AmountUsd) isCreateIntentRequest_Amount() {}

func (*CreateIntentRequest_AmountAsset) isCreateIntentRequest_Amount() {}

type CreateIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentResponse) Reset() {
	*x = CreateIntentResponse{}
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentResponse) ProtoMessage() {}

func (x *CreateIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateIntentResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIntentResponse) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

type GetIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentRequest) Reset() {
	*x = GetIntentRequest{}
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentRequest) ProtoMessage() {}

func (x *GetIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentRequest.ProtoReflect.Descriptor instead.
func (*GetIntentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetIntentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentResponse) Reset() {
	*x = GetIntentResponse{}
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentResponse) ProtoMessage() {}

func (x *GetIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_merchant_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentResponse.ProtoReflect.Descriptor instead.
func (*GetIntentResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_merchant_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetIntentResponse) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

var File_api_v1_merchant_payment_service_proto protoreflect.FileDescriptor

const file_api_v1_merchant_payment_service_proto_rawDesc = "" +
	"\n" +
	"%api/v1/merchant/payment/service.proto\x12\x1ccpay.api.v1.merchant.payment\x1a$api/v1/merchant/payment/intent.proto\"\x80\x01\n" +
	"\x13CreateIntentRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1f\n" +
	"\n" +
	"amount_usd\x18\x02 \x01(\tH\x00R\tamountUsd\x12#\n" +
	"\famount_asset\x18\x03 \x01(\tH\x00R\vamountAssetB\b\n" +
	"\x06amount\"T\n" +
	"\x14CreateIntentResponse\x12<\n" +
	"\x06intent\x18\x01 \x01(\v2$.cpay.api.v1.merchant.payment.IntentR\x06intent\"\"\n" +
	"\x10GetIntentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x11GetIntentResponse\x12<\n" +
	"\x06intent\x18\x01 \x01(\v2$.cpay.api.v1.merchant.payment.IntentR\x06intent2\xf5\x01\n" +
	"\x0ePaymentService\x12u\n" +
	"\fCreateIntent\x121.cpay.api.v1.merchant.payment.CreateIntentRequest\x1a2.cpay.api.v1.merchant.payment.CreateIntentResponse\x12l\n" +
	"\tGetIntent\x12..cpay.api.v1.merchant.payment.GetIntentRequest\x1a/.cpay.api.v1.merchant.payment.GetIntentResponseB6Z4github.com/cpay-dev/proto-go/api/v1/merchant/paymentb\x06proto3"

var (
	file_api_v1_merchant_payment_service_proto_rawDescOnce sync.Once
	file_api_v1_merchant_payment_service_proto_rawDescData []byte
)

func file_api_v1_merchant_payment_service_proto_rawDescGZIP() []byte {
	file_api_v1_merchant_payment_service_proto_rawDescOnce.Do(func() {
		file_api_v1_merchant_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_service_proto_rawDesc), len(file_api_v1_merchant_payment_service_proto_rawDesc)))
	})
	return file_api_v1_merchant_payment_service_proto_rawDescData
}

var file_api_v1_merchant_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_merchant_payment_service_proto_goTypes = []any{
	(*CreateIntentRequest)(nil),  // 0: cpay.api.v1.merchant.payment.CreateIntentRequest
	(*CreateIntentResponse)(nil), // 1: cpay.api.v1.merchant.payment.CreateIntentResponse
	(*GetIntentRequest)(nil),     // 2: cpay.api.v1.merchant.payment.GetIntentRequest
	(*GetIntentResponse)(nil),    // 3: cpay.api.v1.merchant.payment.GetIntentResponse
	(*Intent)(nil),               // 4: cpay.api.v1.merchant.payment.Intent
}
var file_api_v1_merchant_payment_service_proto_depIdxs = []int32{
	4, // 0: cpay.api.v1.merchant.payment.CreateIntentResponse.intent:type_name -> cpay.api.v1.merchant.payment.Intent
	4, // 1: cpay.api.v1.merchant.payment.GetIntentResponse.intent:type_name -> cpay.api.v1.merchant.payment.Intent
	0, // 2: cpay.api.v1.merchant.payment.PaymentService.CreateIntent:input_type -> cpay.api.v1.merchant.payment.CreateIntentRequest
	2, // 3: cpay.api.v1.merchant.payment.PaymentService.GetIntent:input_type -> cpay.api.v1.merchant.payment.GetIntentRequest
	1, // 4: cpay.api.v1.merchant.payment.PaymentService.CreateIntent:output_type -> cpay.api.v1.merchant.payment.CreateIntentResponse
	3, // 5: cpay.api.v1.merchant.payment.PaymentService.GetIntent:output_type -> cpay.api.v1.merchant.payment.GetIntentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_merchant_payment_service_proto_init() }
func file_api_v1_merchant_payment_service_proto_init() {
	if File_api_v1_merchant_payment_service_proto != nil {
		return
	}
	file_api_v1_merchant_payment_intent_proto_init()
	file_api_v1_merchant_payment_service_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateIntentRequest_AmountUsd)(nil),
		(*CreateIntentRequest_AmountAsset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_merchant_payment_service_proto_rawDesc), len(file_api_v1_merchant_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_merchant_payment_service_proto_goTypes,
		DependencyIndexes: file_api_v1_merchant_payment_service_proto_depIdxs,
		MessageInfos:      file_api_v1_merchant_payment_service_proto_msgTypes,
	}.Build()
	File_api_v1_merchant_payment_service_proto = out.File
	file_api_v1_merchant_payment_service_proto_goTypes = nil
	file_api_v1_merchant_payment_service_proto_depIdxs = nil
}
