// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/authn/continue_auth.proto

package authn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContinueAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Method:
	//
	//	*ContinueAuthRequest_ProviderCallback
	Method        isContinueAuthRequest_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueAuthRequest) Reset() {
	*x = ContinueAuthRequest{}
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueAuthRequest) ProtoMessage() {}

func (x *ContinueAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueAuthRequest.ProtoReflect.Descriptor instead.
func (*ContinueAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_continue_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ContinueAuthRequest) GetMethod() isContinueAuthRequest_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *ContinueAuthRequest) GetProviderCallback() *ProviderCallbackMethod {
	if x != nil {
		if x, ok := x.Method.(*ContinueAuthRequest_ProviderCallback); ok {
			return x.ProviderCallback
		}
	}
	return nil
}

type isContinueAuthRequest_Method interface {
	isContinueAuthRequest_Method()
}

type ContinueAuthRequest_ProviderCallback struct {
	ProviderCallback *ProviderCallbackMethod `protobuf:"bytes,1,opt,name=provider_callback,json=providerCallback,proto3,oneof"`
}

func (*ContinueAuthRequest_ProviderCallback) isContinueAuthRequest_Method() {}

type ProviderCallbackMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCallbackMethod) Reset() {
	*x = ProviderCallbackMethod{}
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCallbackMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCallbackMethod) ProtoMessage() {}

func (x *ProviderCallbackMethod) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCallbackMethod.ProtoReflect.Descriptor instead.
func (*ProviderCallbackMethod) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_continue_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderCallbackMethod) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProviderCallbackMethod) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ContinueAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ContinueAuthResponse_ProviderData
	Data          isContinueAuthResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueAuthResponse) Reset() {
	*x = ContinueAuthResponse{}
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueAuthResponse) ProtoMessage() {}

func (x *ContinueAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueAuthResponse.ProtoReflect.Descriptor instead.
func (*ContinueAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_continue_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ContinueAuthResponse) GetData() isContinueAuthResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContinueAuthResponse) GetProviderData() *ProviderCallbackData {
	if x != nil {
		if x, ok := x.Data.(*ContinueAuthResponse_ProviderData); ok {
			return x.ProviderData
		}
	}
	return nil
}

type isContinueAuthResponse_Data interface {
	isContinueAuthResponse_Data()
}

type ContinueAuthResponse_ProviderData struct {
	ProviderData *ProviderCallbackData `protobuf:"bytes,1,opt,name=provider_data,json=providerData,proto3,oneof"`
}

func (*ContinueAuthResponse_ProviderData) isContinueAuthResponse_Data() {}

type ProviderCallbackData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCallbackData) Reset() {
	*x = ProviderCallbackData{}
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCallbackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCallbackData) ProtoMessage() {}

func (x *ProviderCallbackData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_continue_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCallbackData.ProtoReflect.Descriptor instead.
func (*ProviderCallbackData) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_continue_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderCallbackData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProviderCallbackData) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

var File_api_v1_authn_continue_auth_proto protoreflect.FileDescriptor

const file_api_v1_authn_continue_auth_proto_rawDesc = "" +
	"\n" +
	" api/v1/authn/continue_auth.proto\x12\x11cpay.api.v1.authn\"y\n" +
	"\x13ContinueAuthRequest\x12X\n" +
	"\x11provider_callback\x18\x01 \x01(\v2).cpay.api.v1.authn.ProviderCallbackMethodH\x00R\x10providerCallbackB\b\n" +
	"\x06method\"B\n" +
	"\x16ProviderCallbackMethod\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"n\n" +
	"\x14ContinueAuthResponse\x12N\n" +
	"\rprovider_data\x18\x01 \x01(\v2'.cpay.api.v1.authn.ProviderCallbackDataH\x00R\fproviderDataB\x06\n" +
	"\x04data\"S\n" +
	"\x14ProviderCallbackData\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x02 \x01(\bR\remailVerifiedB+Z)github.com/cpay-dev/proto-go/api/v1/authnb\x06proto3"

var (
	file_api_v1_authn_continue_auth_proto_rawDescOnce sync.Once
	file_api_v1_authn_continue_auth_proto_rawDescData []byte
)

func file_api_v1_authn_continue_auth_proto_rawDescGZIP() []byte {
	file_api_v1_authn_continue_auth_proto_rawDescOnce.Do(func() {
		file_api_v1_authn_continue_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_authn_continue_auth_proto_rawDesc), len(file_api_v1_authn_continue_auth_proto_rawDesc)))
	})
	return file_api_v1_authn_continue_auth_proto_rawDescData
}

var file_api_v1_authn_continue_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_authn_continue_auth_proto_goTypes = []any{
	(*ContinueAuthRequest)(nil),    // 0: cpay.api.v1.authn.ContinueAuthRequest
	(*ProviderCallbackMethod)(nil), // 1: cpay.api.v1.authn.ProviderCallbackMethod
	(*ContinueAuthResponse)(nil),   // 2: cpay.api.v1.authn.ContinueAuthResponse
	(*ProviderCallbackData)(nil),   // 3: cpay.api.v1.authn.ProviderCallbackData
}
var file_api_v1_authn_continue_auth_proto_depIdxs = []int32{
	1, // 0: cpay.api.v1.authn.ContinueAuthRequest.provider_callback:type_name -> cpay.api.v1.authn.ProviderCallbackMethod
	3, // 1: cpay.api.v1.authn.ContinueAuthResponse.provider_data:type_name -> cpay.api.v1.authn.ProviderCallbackData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_authn_continue_auth_proto_init() }
func file_api_v1_authn_continue_auth_proto_init() {
	if File_api_v1_authn_continue_auth_proto != nil {
		return
	}
	file_api_v1_authn_continue_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*ContinueAuthRequest_ProviderCallback)(nil),
	}
	file_api_v1_authn_continue_auth_proto_msgTypes[2].OneofWrappers = []any{
		(*ContinueAuthResponse_ProviderData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_authn_continue_auth_proto_rawDesc), len(file_api_v1_authn_continue_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_authn_continue_auth_proto_goTypes,
		DependencyIndexes: file_api_v1_authn_continue_auth_proto_depIdxs,
		MessageInfos:      file_api_v1_authn_continue_auth_proto_msgTypes,
	}.Build()
	File_api_v1_authn_continue_auth_proto = out.File
	file_api_v1_authn_continue_auth_proto_goTypes = nil
	file_api_v1_authn_continue_auth_proto_depIdxs = nil
}
