// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/authn/init_auth.proto

package authn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Method:
	//
	//	*InitAuthRequest_Provider
	//	*InitAuthRequest_Email
	Method        isInitAuthRequest_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAuthRequest) Reset() {
	*x = InitAuthRequest{}
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAuthRequest) ProtoMessage() {}

func (x *InitAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAuthRequest.ProtoReflect.Descriptor instead.
func (*InitAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_init_auth_proto_rawDescGZIP(), []int{0}
}

func (x *InitAuthRequest) GetMethod() isInitAuthRequest_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *InitAuthRequest) GetProvider() *ProviderMethod {
	if x != nil {
		if x, ok := x.Method.(*InitAuthRequest_Provider); ok {
			return x.Provider
		}
	}
	return nil
}

func (x *InitAuthRequest) GetEmail() *EmailMethod {
	if x != nil {
		if x, ok := x.Method.(*InitAuthRequest_Email); ok {
			return x.Email
		}
	}
	return nil
}

type isInitAuthRequest_Method interface {
	isInitAuthRequest_Method()
}

type InitAuthRequest_Provider struct {
	Provider *ProviderMethod `protobuf:"bytes,1,opt,name=provider,proto3,oneof"`
}

type InitAuthRequest_Email struct {
	Email *EmailMethod `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*InitAuthRequest_Provider) isInitAuthRequest_Method() {}

func (*InitAuthRequest_Email) isInitAuthRequest_Method() {}

type ProviderMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      AuthProvider           `protobuf:"varint,1,opt,name=provider,proto3,enum=cpay.api.v1.authn.AuthProvider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMethod) Reset() {
	*x = ProviderMethod{}
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMethod) ProtoMessage() {}

func (x *ProviderMethod) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMethod.ProtoReflect.Descriptor instead.
func (*ProviderMethod) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_init_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderMethod) GetProvider() AuthProvider {
	if x != nil {
		return x.Provider
	}
	return AuthProvider_AUTH_PROVIDER_UNSPECIFIED
}

type EmailMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailMethod) Reset() {
	*x = EmailMethod{}
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailMethod) ProtoMessage() {}

func (x *EmailMethod) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailMethod.ProtoReflect.Descriptor instead.
func (*EmailMethod) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_init_auth_proto_rawDescGZIP(), []int{2}
}

func (x *EmailMethod) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type InitAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Continuation:
	//
	//	*InitAuthResponse_AuthUrl
	Continuation  isInitAuthResponse_Continuation `protobuf_oneof:"continuation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAuthResponse) Reset() {
	*x = InitAuthResponse{}
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAuthResponse) ProtoMessage() {}

func (x *InitAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_authn_init_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAuthResponse.ProtoReflect.Descriptor instead.
func (*InitAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_authn_init_auth_proto_rawDescGZIP(), []int{3}
}

func (x *InitAuthResponse) GetContinuation() isInitAuthResponse_Continuation {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *InitAuthResponse) GetAuthUrl() string {
	if x != nil {
		if x, ok := x.Continuation.(*InitAuthResponse_AuthUrl); ok {
			return x.AuthUrl
		}
	}
	return ""
}

type isInitAuthResponse_Continuation interface {
	isInitAuthResponse_Continuation()
}

type InitAuthResponse_AuthUrl struct {
	AuthUrl string `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3,oneof"`
}

func (*InitAuthResponse_AuthUrl) isInitAuthResponse_Continuation() {}

var File_api_v1_authn_init_auth_proto protoreflect.FileDescriptor

const file_api_v1_authn_init_auth_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1/authn/init_auth.proto\x12\x11cpay.api.v1.authn\x1a\x1bapi/v1/authn/provider.proto\"\x94\x01\n" +
	"\x0fInitAuthRequest\x12?\n" +
	"\bprovider\x18\x01 \x01(\v2!.cpay.api.v1.authn.ProviderMethodH\x00R\bprovider\x126\n" +
	"\x05email\x18\x02 \x01(\v2\x1e.cpay.api.v1.authn.EmailMethodH\x00R\x05emailB\b\n" +
	"\x06method\"M\n" +
	"\x0eProviderMethod\x12;\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1f.cpay.api.v1.authn.AuthProviderR\bprovider\"#\n" +
	"\vEmailMethod\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"?\n" +
	"\x10InitAuthResponse\x12\x1b\n" +
	"\bauth_url\x18\x01 \x01(\tH\x00R\aauthUrlB\x0e\n" +
	"\fcontinuationB+Z)github.com/cpay-dev/proto-go/api/v1/authnb\x06proto3"

var (
	file_api_v1_authn_init_auth_proto_rawDescOnce sync.Once
	file_api_v1_authn_init_auth_proto_rawDescData []byte
)

func file_api_v1_authn_init_auth_proto_rawDescGZIP() []byte {
	file_api_v1_authn_init_auth_proto_rawDescOnce.Do(func() {
		file_api_v1_authn_init_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_authn_init_auth_proto_rawDesc), len(file_api_v1_authn_init_auth_proto_rawDesc)))
	})
	return file_api_v1_authn_init_auth_proto_rawDescData
}

var file_api_v1_authn_init_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_authn_init_auth_proto_goTypes = []any{
	(*InitAuthRequest)(nil),  // 0: cpay.api.v1.authn.InitAuthRequest
	(*ProviderMethod)(nil),   // 1: cpay.api.v1.authn.ProviderMethod
	(*EmailMethod)(nil),      // 2: cpay.api.v1.authn.EmailMethod
	(*InitAuthResponse)(nil), // 3: cpay.api.v1.authn.InitAuthResponse
	(AuthProvider)(0),        // 4: cpay.api.v1.authn.AuthProvider
}
var file_api_v1_authn_init_auth_proto_depIdxs = []int32{
	1, // 0: cpay.api.v1.authn.InitAuthRequest.provider:type_name -> cpay.api.v1.authn.ProviderMethod
	2, // 1: cpay.api.v1.authn.InitAuthRequest.email:type_name -> cpay.api.v1.authn.EmailMethod
	4, // 2: cpay.api.v1.authn.ProviderMethod.provider:type_name -> cpay.api.v1.authn.AuthProvider
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_authn_init_auth_proto_init() }
func file_api_v1_authn_init_auth_proto_init() {
	if File_api_v1_authn_init_auth_proto != nil {
		return
	}
	file_api_v1_authn_provider_proto_init()
	file_api_v1_authn_init_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*InitAuthRequest_Provider)(nil),
		(*InitAuthRequest_Email)(nil),
	}
	file_api_v1_authn_init_auth_proto_msgTypes[3].OneofWrappers = []any{
		(*InitAuthResponse_AuthUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_authn_init_auth_proto_rawDesc), len(file_api_v1_authn_init_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_authn_init_auth_proto_goTypes,
		DependencyIndexes: file_api_v1_authn_init_auth_proto_depIdxs,
		MessageInfos:      file_api_v1_authn_init_auth_proto_msgTypes,
	}.Build()
	File_api_v1_authn_init_auth_proto = out.File
	file_api_v1_authn_init_auth_proto_goTypes = nil
	file_api_v1_authn_init_auth_proto_depIdxs = nil
}
