// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/authn/provider.proto

package authn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthProvider int32

const (
	AuthProvider_AUTH_PROVIDER_UNSPECIFIED AuthProvider = 0
	AuthProvider_AUTH_PROVIDER_GOOGLE      AuthProvider = 1
)

// Enum value maps for AuthProvider.
var (
	AuthProvider_name = map[int32]string{
		0: "AUTH_PROVIDER_UNSPECIFIED",
		1: "AUTH_PROVIDER_GOOGLE",
	}
	AuthProvider_value = map[string]int32{
		"AUTH_PROVIDER_UNSPECIFIED": 0,
		"AUTH_PROVIDER_GOOGLE":      1,
	}
)

func (x AuthProvider) Enum() *AuthProvider {
	p := new(AuthProvider)
	*p = x
	return p
}

func (x AuthProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_authn_provider_proto_enumTypes[0].Descriptor()
}

func (AuthProvider) Type() protoreflect.EnumType {
	return &file_api_v1_authn_provider_proto_enumTypes[0]
}

func (x AuthProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthProvider.Descriptor instead.
func (AuthProvider) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_authn_provider_proto_rawDescGZIP(), []int{0}
}

var File_api_v1_authn_provider_proto protoreflect.FileDescriptor

const file_api_v1_authn_provider_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v1/authn/provider.proto\x12\x11cpay.api.v1.authn*G\n" +
	"\fAuthProvider\x12\x1d\n" +
	"\x19AUTH_PROVIDER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUTH_PROVIDER_GOOGLE\x10\x01B+Z)github.com/cpay-dev/proto-go/api/v1/authnb\x06proto3"

var (
	file_api_v1_authn_provider_proto_rawDescOnce sync.Once
	file_api_v1_authn_provider_proto_rawDescData []byte
)

func file_api_v1_authn_provider_proto_rawDescGZIP() []byte {
	file_api_v1_authn_provider_proto_rawDescOnce.Do(func() {
		file_api_v1_authn_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_authn_provider_proto_rawDesc), len(file_api_v1_authn_provider_proto_rawDesc)))
	})
	return file_api_v1_authn_provider_proto_rawDescData
}

var file_api_v1_authn_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_authn_provider_proto_goTypes = []any{
	(AuthProvider)(0), // 0: cpay.api.v1.authn.AuthProvider
}
var file_api_v1_authn_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_authn_provider_proto_init() }
func file_api_v1_authn_provider_proto_init() {
	if File_api_v1_authn_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_authn_provider_proto_rawDesc), len(file_api_v1_authn_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_authn_provider_proto_goTypes,
		DependencyIndexes: file_api_v1_authn_provider_proto_depIdxs,
		EnumInfos:         file_api_v1_authn_provider_proto_enumTypes,
	}.Build()
	File_api_v1_authn_provider_proto = out.File
	file_api_v1_authn_provider_proto_goTypes = nil
	file_api_v1_authn_provider_proto_depIdxs = nil
}
