// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/authn/service.proto

package authn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_authn_service_proto protoreflect.FileDescriptor

const file_api_v1_authn_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/authn/service.proto\x12\x11cpay.api.v1.authn\x1a\x1capi/v1/authn/init_auth.proto2c\n" +
	"\fAuthnService\x12S\n" +
	"\bInitAuth\x12\".cpay.api.v1.authn.InitAuthRequest\x1a#.cpay.api.v1.authn.InitAuthResponseB+Z)github.com/cpay-dev/proto-go/api/v1/authnb\x06proto3"

var file_api_v1_authn_service_proto_goTypes = []any{
	(*InitAuthRequest)(nil),  // 0: cpay.api.v1.authn.InitAuthRequest
	(*InitAuthResponse)(nil), // 1: cpay.api.v1.authn.InitAuthResponse
}
var file_api_v1_authn_service_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.authn.AuthnService.InitAuth:input_type -> cpay.api.v1.authn.InitAuthRequest
	1, // 1: cpay.api.v1.authn.AuthnService.InitAuth:output_type -> cpay.api.v1.authn.InitAuthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_authn_service_proto_init() }
func file_api_v1_authn_service_proto_init() {
	if File_api_v1_authn_service_proto != nil {
		return
	}
	file_api_v1_authn_init_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_authn_service_proto_rawDesc), len(file_api_v1_authn_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_authn_service_proto_goTypes,
		DependencyIndexes: file_api_v1_authn_service_proto_depIdxs,
	}.Build()
	File_api_v1_authn_service_proto = out.File
	file_api_v1_authn_service_proto_goTypes = nil
	file_api_v1_authn_service_proto_depIdxs = nil
}
