// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/user/get_user_profile.proto

package user

import (
	authn "github.com/cpay-dev/proto-go/api/v1/authn"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      authn.AuthProvider     `protobuf:"varint,1,opt,name=provider,proto3,enum=cpay.api.v1.authn.AuthProvider" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_api_v1_user_get_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_get_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_get_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileRequest) GetProvider() authn.AuthProvider {
	if x != nil {
		return x.Provider
	}
	return authn.AuthProvider(0)
}

func (x *GetUserProfileRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_api_v1_user_get_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_get_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_get_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_api_v1_user_get_user_profile_proto protoreflect.FileDescriptor

const file_api_v1_user_get_user_profile_proto_rawDesc = "" +
	"\n" +
	"\"api/v1/user/get_user_profile.proto\x12\x10cpay.api.v1.user\x1a\x1bapi/v1/authn/provider.proto\x1a\x16api/v1/user/user.proto\"t\n" +
	"\x15GetUserProfileRequest\x12;\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1f.cpay.api.v1.authn.AuthProviderR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"Q\n" +
	"\x16GetUserProfileResponse\x127\n" +
	"\aprofile\x18\x01 \x01(\v2\x1d.cpay.api.v1.user.UserProfileR\aprofileB*Z(github.com/cpay-dev/proto-go/api/v1/userb\x06proto3"

var (
	file_api_v1_user_get_user_profile_proto_rawDescOnce sync.Once
	file_api_v1_user_get_user_profile_proto_rawDescData []byte
)

func file_api_v1_user_get_user_profile_proto_rawDescGZIP() []byte {
	file_api_v1_user_get_user_profile_proto_rawDescOnce.Do(func() {
		file_api_v1_user_get_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_user_get_user_profile_proto_rawDesc), len(file_api_v1_user_get_user_profile_proto_rawDesc)))
	})
	return file_api_v1_user_get_user_profile_proto_rawDescData
}

var file_api_v1_user_get_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_user_get_user_profile_proto_goTypes = []any{
	(*GetUserProfileRequest)(nil),  // 0: cpay.api.v1.user.GetUserProfileRequest
	(*GetUserProfileResponse)(nil), // 1: cpay.api.v1.user.GetUserProfileResponse
	(authn.AuthProvider)(0),        // 2: cpay.api.v1.authn.AuthProvider
	(*UserProfile)(nil),            // 3: cpay.api.v1.user.UserProfile
}
var file_api_v1_user_get_user_profile_proto_depIdxs = []int32{
	2, // 0: cpay.api.v1.user.GetUserProfileRequest.provider:type_name -> cpay.api.v1.authn.AuthProvider
	3, // 1: cpay.api.v1.user.GetUserProfileResponse.profile:type_name -> cpay.api.v1.user.UserProfile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_user_get_user_profile_proto_init() }
func file_api_v1_user_get_user_profile_proto_init() {
	if File_api_v1_user_get_user_profile_proto != nil {
		return
	}
	file_api_v1_user_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_get_user_profile_proto_rawDesc), len(file_api_v1_user_get_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_user_get_user_profile_proto_goTypes,
		DependencyIndexes: file_api_v1_user_get_user_profile_proto_depIdxs,
		MessageInfos:      file_api_v1_user_get_user_profile_proto_msgTypes,
	}.Build()
	File_api_v1_user_get_user_profile_proto = out.File
	file_api_v1_user_get_user_profile_proto_goTypes = nil
	file_api_v1_user_get_user_profile_proto_depIdxs = nil
}
