// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/user/identity.proto

package user

import (
	authn "github.com/cpay-dev/proto-go/api/v1/authn"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityStatus int32

const (
	IdentityStatus_IDENTITY_STATUS_UNSPECIFIED          IdentityStatus = 0
	IdentityStatus_IDENTITY_STATUS_PENDING_VERIFICATION IdentityStatus = 1
	IdentityStatus_IDENTITY_STATUS_ACTIVE               IdentityStatus = 2
	IdentityStatus_IDENTITY_STATUS_INACTIVE             IdentityStatus = 3
)

// Enum value maps for IdentityStatus.
var (
	IdentityStatus_name = map[int32]string{
		0: "IDENTITY_STATUS_UNSPECIFIED",
		1: "IDENTITY_STATUS_PENDING_VERIFICATION",
		2: "IDENTITY_STATUS_ACTIVE",
		3: "IDENTITY_STATUS_INACTIVE",
	}
	IdentityStatus_value = map[string]int32{
		"IDENTITY_STATUS_UNSPECIFIED":          0,
		"IDENTITY_STATUS_PENDING_VERIFICATION": 1,
		"IDENTITY_STATUS_ACTIVE":               2,
		"IDENTITY_STATUS_INACTIVE":             3,
	}
)

func (x IdentityStatus) Enum() *IdentityStatus {
	p := new(IdentityStatus)
	*p = x
	return p
}

func (x IdentityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_user_identity_proto_enumTypes[0].Descriptor()
}

func (IdentityStatus) Type() protoreflect.EnumType {
	return &file_api_v1_user_identity_proto_enumTypes[0]
}

func (x IdentityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityStatus.Descriptor instead.
func (IdentityStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_user_identity_proto_rawDescGZIP(), []int{0}
}

type GoogleIdentityMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailVerified bool                   `protobuf:"varint,1,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleIdentityMetadata) Reset() {
	*x = GoogleIdentityMetadata{}
	mi := &file_api_v1_user_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleIdentityMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleIdentityMetadata) ProtoMessage() {}

func (x *GoogleIdentityMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleIdentityMetadata.ProtoReflect.Descriptor instead.
func (*GoogleIdentityMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1_user_identity_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleIdentityMetadata) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

type UserIdentity struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status     IdentityStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=cpay.api.v1.user.IdentityStatus" json:"status,omitempty"`
	Provider   authn.AuthProvider     `protobuf:"varint,3,opt,name=provider,proto3,enum=cpay.api.v1.authn.AuthProvider" json:"provider,omitempty"`
	Identifier string                 `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//
	//	*UserIdentity_Google
	Metadata      isUserIdentity_Metadata `protobuf_oneof:"metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_api_v1_user_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_api_v1_user_identity_proto_rawDescGZIP(), []int{1}
}

func (x *UserIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserIdentity) GetStatus() IdentityStatus {
	if x != nil {
		return x.Status
	}
	return IdentityStatus_IDENTITY_STATUS_UNSPECIFIED
}

func (x *UserIdentity) GetProvider() authn.AuthProvider {
	if x != nil {
		return x.Provider
	}
	return authn.AuthProvider(0)
}

func (x *UserIdentity) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *UserIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserIdentity) GetMetadata() isUserIdentity_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserIdentity) GetGoogle() *GoogleIdentityMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*UserIdentity_Google); ok {
			return x.Google
		}
	}
	return nil
}

type isUserIdentity_Metadata interface {
	isUserIdentity_Metadata()
}

type UserIdentity_Google struct {
	Google *GoogleIdentityMetadata `protobuf:"bytes,20,opt,name=google,proto3,oneof"`
}

func (*UserIdentity_Google) isUserIdentity_Metadata() {}

var File_api_v1_user_identity_proto protoreflect.FileDescriptor

const file_api_v1_user_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/user/identity.proto\x12\x10cpay.api.v1.user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bapi/v1/authn/provider.proto\"?\n" +
	"\x16GoogleIdentityMetadata\x12%\n" +
	"\x0eemail_verified\x18\x01 \x01(\bR\remailVerified\"\xc0\x02\n" +
	"\fUserIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .cpay.api.v1.user.IdentityStatusR\x06status\x12;\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x1f.cpay.api.v1.authn.AuthProviderR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x04 \x01(\tR\n" +
	"identifier\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x06google\x18\x14 \x01(\v2(.cpay.api.v1.user.GoogleIdentityMetadataH\x00R\x06googleB\n" +
	"\n" +
	"\bmetadata*\x95\x01\n" +
	"\x0eIdentityStatus\x12\x1f\n" +
	"\x1bIDENTITY_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$IDENTITY_STATUS_PENDING_VERIFICATION\x10\x01\x12\x1a\n" +
	"\x16IDENTITY_STATUS_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18IDENTITY_STATUS_INACTIVE\x10\x03B*Z(github.com/cpay-dev/proto-go/api/v1/userb\x06proto3"

var (
	file_api_v1_user_identity_proto_rawDescOnce sync.Once
	file_api_v1_user_identity_proto_rawDescData []byte
)

func file_api_v1_user_identity_proto_rawDescGZIP() []byte {
	file_api_v1_user_identity_proto_rawDescOnce.Do(func() {
		file_api_v1_user_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_user_identity_proto_rawDesc), len(file_api_v1_user_identity_proto_rawDesc)))
	})
	return file_api_v1_user_identity_proto_rawDescData
}

var file_api_v1_user_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_user_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_user_identity_proto_goTypes = []any{
	(IdentityStatus)(0),            // 0: cpay.api.v1.user.IdentityStatus
	(*GoogleIdentityMetadata)(nil), // 1: cpay.api.v1.user.GoogleIdentityMetadata
	(*UserIdentity)(nil),           // 2: cpay.api.v1.user.UserIdentity
	(authn.AuthProvider)(0),        // 3: cpay.api.v1.authn.AuthProvider
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_api_v1_user_identity_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.user.UserIdentity.status:type_name -> cpay.api.v1.user.IdentityStatus
	3, // 1: cpay.api.v1.user.UserIdentity.provider:type_name -> cpay.api.v1.authn.AuthProvider
	4, // 2: cpay.api.v1.user.UserIdentity.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: cpay.api.v1.user.UserIdentity.google:type_name -> cpay.api.v1.user.GoogleIdentityMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_user_identity_proto_init() }
func file_api_v1_user_identity_proto_init() {
	if File_api_v1_user_identity_proto != nil {
		return
	}
	file_api_v1_user_identity_proto_msgTypes[1].OneofWrappers = []any{
		(*UserIdentity_Google)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_identity_proto_rawDesc), len(file_api_v1_user_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_user_identity_proto_goTypes,
		DependencyIndexes: file_api_v1_user_identity_proto_depIdxs,
		EnumInfos:         file_api_v1_user_identity_proto_enumTypes,
		MessageInfos:      file_api_v1_user_identity_proto_msgTypes,
	}.Build()
	File_api_v1_user_identity_proto = out.File
	file_api_v1_user_identity_proto_goTypes = nil
	file_api_v1_user_identity_proto_depIdxs = nil
}
