// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/user/merchant.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantStatus int32

const (
	MerchantStatus_MERCHANT_STATUS_UNSPECIFIED          MerchantStatus = 0
	MerchantStatus_MERCHANT_STATUS_PENDING_VERIFICATION MerchantStatus = 1
	MerchantStatus_MERCHANT_STATUS_ACTIVE               MerchantStatus = 2
	MerchantStatus_MERCHANT_STATUS_INACTIVE             MerchantStatus = 3
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "MERCHANT_STATUS_UNSPECIFIED",
		1: "MERCHANT_STATUS_PENDING_VERIFICATION",
		2: "MERCHANT_STATUS_ACTIVE",
		3: "MERCHANT_STATUS_INACTIVE",
	}
	MerchantStatus_value = map[string]int32{
		"MERCHANT_STATUS_UNSPECIFIED":          0,
		"MERCHANT_STATUS_PENDING_VERIFICATION": 1,
		"MERCHANT_STATUS_ACTIVE":               2,
		"MERCHANT_STATUS_INACTIVE":             3,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_user_merchant_proto_enumTypes[0].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_api_v1_user_merchant_proto_enumTypes[0]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_user_merchant_proto_rawDescGZIP(), []int{0}
}

type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        MerchantStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=cpay.api.v1.user.MerchantStatus" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_api_v1_user_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_api_v1_user_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Merchant) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Merchant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Merchant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_v1_user_merchant_proto protoreflect.FileDescriptor

const file_api_v1_user_merchant_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/user/merchant.proto\x12\x10cpay.api.v1.user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\bMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .cpay.api.v1.user.MerchantStatusR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\x95\x01\n" +
	"\x0eMerchantStatus\x12\x1f\n" +
	"\x1bMERCHANT_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$MERCHANT_STATUS_PENDING_VERIFICATION\x10\x01\x12\x1a\n" +
	"\x16MERCHANT_STATUS_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18MERCHANT_STATUS_INACTIVE\x10\x03B*Z(github.com/cpay-dev/proto-go/api/v1/userb\x06proto3"

var (
	file_api_v1_user_merchant_proto_rawDescOnce sync.Once
	file_api_v1_user_merchant_proto_rawDescData []byte
)

func file_api_v1_user_merchant_proto_rawDescGZIP() []byte {
	file_api_v1_user_merchant_proto_rawDescOnce.Do(func() {
		file_api_v1_user_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_user_merchant_proto_rawDesc), len(file_api_v1_user_merchant_proto_rawDesc)))
	})
	return file_api_v1_user_merchant_proto_rawDescData
}

var file_api_v1_user_merchant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_user_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v1_user_merchant_proto_goTypes = []any{
	(MerchantStatus)(0),           // 0: cpay.api.v1.user.MerchantStatus
	(*Merchant)(nil),              // 1: cpay.api.v1.user.Merchant
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_v1_user_merchant_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.user.Merchant.status:type_name -> cpay.api.v1.user.MerchantStatus
	2, // 1: cpay.api.v1.user.Merchant.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_user_merchant_proto_init() }
func file_api_v1_user_merchant_proto_init() {
	if File_api_v1_user_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_merchant_proto_rawDesc), len(file_api_v1_user_merchant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_user_merchant_proto_goTypes,
		DependencyIndexes: file_api_v1_user_merchant_proto_depIdxs,
		EnumInfos:         file_api_v1_user_merchant_proto_enumTypes,
		MessageInfos:      file_api_v1_user_merchant_proto_msgTypes,
	}.Build()
	File_api_v1_user_merchant_proto = out.File
	file_api_v1_user_merchant_proto_goTypes = nil
	file_api_v1_user_merchant_proto_depIdxs = nil
}
