// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/user/service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_user_service_proto protoreflect.FileDescriptor

const file_api_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/v1/user/service.proto\x12\x10cpay.api.v1.user\x1a\"api/v1/user/get_user_profile.proto2r\n" +
	"\vUserService\x12c\n" +
	"\x0eGetUserProfile\x12'.cpay.api.v1.user.GetUserProfileRequest\x1a(.cpay.api.v1.user.GetUserProfileResponseB*Z(github.com/cpay-dev/proto-go/api/v1/userb\x06proto3"

var file_api_v1_user_service_proto_goTypes = []any{
	(*GetUserProfileRequest)(nil),  // 0: cpay.api.v1.user.GetUserProfileRequest
	(*GetUserProfileResponse)(nil), // 1: cpay.api.v1.user.GetUserProfileResponse
}
var file_api_v1_user_service_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.user.UserService.GetUserProfile:input_type -> cpay.api.v1.user.GetUserProfileRequest
	1, // 1: cpay.api.v1.user.UserService.GetUserProfile:output_type -> cpay.api.v1.user.GetUserProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_user_service_proto_init() }
func file_api_v1_user_service_proto_init() {
	if File_api_v1_user_service_proto != nil {
		return
	}
	file_api_v1_user_get_user_profile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_service_proto_rawDesc), len(file_api_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_user_service_proto_goTypes,
		DependencyIndexes: file_api_v1_user_service_proto_depIdxs,
	}.Build()
	File_api_v1_user_service_proto = out.File
	file_api_v1_user_service_proto_goTypes = nil
	file_api_v1_user_service_proto_depIdxs = nil
}
