// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED          UserStatus = 0
	UserStatus_USER_STATUS_PENDING_VERIFICATION UserStatus = 1
	UserStatus_USER_STATUS_ACTIVE               UserStatus = 2
	UserStatus_USER_STATUS_INACTIVE             UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_PENDING_VERIFICATION",
		2: "USER_STATUS_ACTIVE",
		3: "USER_STATUS_INACTIVE",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED":          0,
		"USER_STATUS_PENDING_VERIFICATION": 1,
		"USER_STATUS_ACTIVE":               2,
		"USER_STATUS_INACTIVE":             3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_user_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_api_v1_user_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_user_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status            UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=cpay.api.v1.user.UserStatus" json:"status,omitempty"`
	PrimaryMerchantId string                 `protobuf:"bytes,3,opt,name=primary_merchant_id,json=primaryMerchantId,proto3" json:"primary_merchant_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_v1_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetPrimaryMerchantId() string {
	if x != nil {
		return x.PrimaryMerchantId
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Identities    []*UserIdentity        `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	Merchants     []*Merchant            `protobuf:"bytes,3,rep,name=merchants,proto3" json:"merchants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_v1_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserProfile) GetIdentities() []*UserIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *UserProfile) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

var File_api_v1_user_user_proto protoreflect.FileDescriptor

const file_api_v1_user_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/user/user.proto\x12\x10cpay.api.v1.user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/v1/user/identity.proto\x1a\x1aapi/v1/user/merchant.proto\"\xb7\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.cpay.api.v1.user.UserStatusR\x06status\x12.\n" +
	"\x13primary_merchant_id\x18\x03 \x01(\tR\x11primaryMerchantId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb3\x01\n" +
	"\vUserProfile\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.cpay.api.v1.user.UserR\x04user\x12>\n" +
	"\n" +
	"identities\x18\x02 \x03(\v2\x1e.cpay.api.v1.user.UserIdentityR\n" +
	"identities\x128\n" +
	"\tmerchants\x18\x03 \x03(\v2\x1a.cpay.api.v1.user.MerchantR\tmerchants*\x81\x01\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" USER_STATUS_PENDING_VERIFICATION\x10\x01\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x02\x12\x18\n" +
	"\x14USER_STATUS_INACTIVE\x10\x03B*Z(github.com/cpay-dev/proto-go/api/v1/userb\x06proto3"

var (
	file_api_v1_user_user_proto_rawDescOnce sync.Once
	file_api_v1_user_user_proto_rawDescData []byte
)

func file_api_v1_user_user_proto_rawDescGZIP() []byte {
	file_api_v1_user_user_proto_rawDescOnce.Do(func() {
		file_api_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_user_user_proto_rawDesc), len(file_api_v1_user_user_proto_rawDesc)))
	})
	return file_api_v1_user_user_proto_rawDescData
}

var file_api_v1_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_user_user_proto_goTypes = []any{
	(UserStatus)(0),               // 0: cpay.api.v1.user.UserStatus
	(*User)(nil),                  // 1: cpay.api.v1.user.User
	(*UserProfile)(nil),           // 2: cpay.api.v1.user.UserProfile
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*UserIdentity)(nil),          // 4: cpay.api.v1.user.UserIdentity
	(*Merchant)(nil),              // 5: cpay.api.v1.user.Merchant
}
var file_api_v1_user_user_proto_depIdxs = []int32{
	0, // 0: cpay.api.v1.user.User.status:type_name -> cpay.api.v1.user.UserStatus
	3, // 1: cpay.api.v1.user.User.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: cpay.api.v1.user.UserProfile.user:type_name -> cpay.api.v1.user.User
	4, // 3: cpay.api.v1.user.UserProfile.identities:type_name -> cpay.api.v1.user.UserIdentity
	5, // 4: cpay.api.v1.user.UserProfile.merchants:type_name -> cpay.api.v1.user.Merchant
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_user_user_proto_init() }
func file_api_v1_user_user_proto_init() {
	if File_api_v1_user_user_proto != nil {
		return
	}
	file_api_v1_user_identity_proto_init()
	file_api_v1_user_merchant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_user_proto_rawDesc), len(file_api_v1_user_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_user_user_proto_goTypes,
		DependencyIndexes: file_api_v1_user_user_proto_depIdxs,
		EnumInfos:         file_api_v1_user_user_proto_enumTypes,
		MessageInfos:      file_api_v1_user_user_proto_msgTypes,
	}.Build()
	File_api_v1_user_user_proto = out.File
	file_api_v1_user_user_proto_goTypes = nil
	file_api_v1_user_user_proto_depIdxs = nil
}
