// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/v1/wallet/service.proto

package wallet

import (
	blockchain "github.com/cpay-dev/proto-go/api/v1/blockchain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         blockchain.ChainID     `protobuf:"varint,1,opt,name=chain,proto3,enum=cpay.api.v1.blockchain.ChainID" json:"chain,omitempty"`
	TransitKey    []byte                 `protobuf:"bytes,2,opt,name=transit_key,json=transitKey,proto3" json:"transit_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_v1_wallet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetChain() blockchain.ChainID {
	if x != nil {
		return x.Chain
	}
	return blockchain.ChainID(0)
}

func (x *CreateWalletRequest) GetTransitKey() []byte {
	if x != nil {
		return x.TransitKey
	}
	return nil
}

type CreateWalletResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KekVersion          uint32                 `protobuf:"varint,1,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	EncryptedPrivateKey []byte                 `protobuf:"bytes,2,opt,name=encrypted_private_key,json=encryptedPrivateKey,proto3" json:"encrypted_private_key,omitempty"`
	PublicKey           string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_api_v1_wallet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResponse) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *CreateWalletResponse) GetEncryptedPrivateKey() []byte {
	if x != nil {
		return x.EncryptedPrivateKey
	}
	return nil
}

func (x *CreateWalletResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_api_v1_wallet_service_proto protoreflect.FileDescriptor

const file_api_v1_wallet_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v1/wallet/service.proto\x12\x12cpay.api.v1.wallet\x1a api/v1/blockchain/chain_id.proto\"m\n" +
	"\x13CreateWalletRequest\x125\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x1f.cpay.api.v1.blockchain.ChainIDR\x05chain\x12\x1f\n" +
	"\vtransit_key\x18\x02 \x01(\fR\n" +
	"transitKey\"\x8a\x01\n" +
	"\x14CreateWalletResponse\x12\x1f\n" +
	"\vkek_version\x18\x01 \x01(\rR\n" +
	"kekVersion\x122\n" +
	"\x15encrypted_private_key\x18\x02 \x01(\fR\x13encryptedPrivateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey2r\n" +
	"\rWalletService\x12a\n" +
	"\fCreateWallet\x12'.cpay.api.v1.wallet.CreateWalletRequest\x1a(.cpay.api.v1.wallet.CreateWalletResponseB,Z*github.com/cpay-dev/proto-go/api/v1/walletb\x06proto3"

var (
	file_api_v1_wallet_service_proto_rawDescOnce sync.Once
	file_api_v1_wallet_service_proto_rawDescData []byte
)

func file_api_v1_wallet_service_proto_rawDescGZIP() []byte {
	file_api_v1_wallet_service_proto_rawDescOnce.Do(func() {
		file_api_v1_wallet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_wallet_service_proto_rawDesc), len(file_api_v1_wallet_service_proto_rawDesc)))
	})
	return file_api_v1_wallet_service_proto_rawDescData
}

var file_api_v1_wallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_wallet_service_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),  // 0: cpay.api.v1.wallet.CreateWalletRequest
	(*CreateWalletResponse)(nil), // 1: cpay.api.v1.wallet.CreateWalletResponse
	(blockchain.ChainID)(0),      // 2: cpay.api.v1.blockchain.ChainID
}
var file_api_v1_wallet_service_proto_depIdxs = []int32{
	2, // 0: cpay.api.v1.wallet.CreateWalletRequest.chain:type_name -> cpay.api.v1.blockchain.ChainID
	0, // 1: cpay.api.v1.wallet.WalletService.CreateWallet:input_type -> cpay.api.v1.wallet.CreateWalletRequest
	1, // 2: cpay.api.v1.wallet.WalletService.CreateWallet:output_type -> cpay.api.v1.wallet.CreateWalletResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_wallet_service_proto_init() }
func file_api_v1_wallet_service_proto_init() {
	if File_api_v1_wallet_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_wallet_service_proto_rawDesc), len(file_api_v1_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_wallet_service_proto_goTypes,
		DependencyIndexes: file_api_v1_wallet_service_proto_depIdxs,
		MessageInfos:      file_api_v1_wallet_service_proto_msgTypes,
	}.Build()
	File_api_v1_wallet_service_proto = out.File
	file_api_v1_wallet_service_proto_goTypes = nil
	file_api_v1_wallet_service_proto_depIdxs = nil
}
